// @generated by mcu-protocol/build.rs from schema_def.rs — DO NOT EDIT.
// Regenerated on every build; hand edits are overwritten.

use crate::codec::Cursor;
use crate::codec::Decode;
use crate::codec::DecodeError;
use crate::codec::Encode;
use crate::codec::get_f32;
use crate::codec::get_i32;
use crate::codec::get_u8;
use crate::codec::get_u16;
use crate::codec::get_u32;
use crate::codec::get_u64;
use crate::codec::put_f32;
use crate::codec::put_i32;
use crate::codec::put_u8;
use crate::codec::put_u16;
use crate::codec::put_u32;
use crate::codec::put_u64;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u16)]
pub enum MessageKind {
    Identify = 0x0001,
    IdentifyResponse = 0x0002,
    ConfigureAxes = 0x0030,
    ConfigureAxesResponse = 0x0031,
    QueryRuntimeCaps = 0x0040,
    RuntimeCapsResponse = 0x0041,
    ClaimHandshake = 0x0042,
    ClaimHandshakeReply = 0x0043,
    QueryMotorState = 0x0044,
    MotorStateResponse = 0x0045,
    PushPieces = 0x0060,
    PushPiecesResponse = 0x0061,
    StartCapture = 0x0068,
    StartCaptureResponse = 0x0069,
    StopCapture = 0x006A,
    StopCaptureResponse = 0x006B,
    ResonanceBuzz = 0x006C,
    ResonanceBuzzResponse = 0x006D,
    ArmSensorlessEndstop = 0x006E,
    ArmSensorlessEndstopResponse = 0x006F,
    SetTorque = 0x0070,
    SetTorqueResponse = 0x0071,
    Stop = 0x0072,
    StopResponse = 0x0073,
    SetDriveLimits = 0x0074,
    SetDriveLimitsResponse = 0x0075,
    RestoreDriveLimits = 0x0076,
    RestoreDriveLimitsResponse = 0x0077,
    ResumeStream = 0x0078,
    ResumeStreamResponse = 0x0079,
    SeedServoHome = 0x007A,
    SeedServoHomeResponse = 0x007B,
    SdoRead = 0x007C,
    SdoReadResponse = 0x007D,
    SdoWrite = 0x007E,
    SdoWriteResponse = 0x007F,
    FaultEvent = 0x0082,
    StatusHeartbeat = 0x0083,
    McuLog = 0x0084,
    EndstopTrip = 0x0085,
    SetStrainComp = 0x0086,
    SetStrainCompResponse = 0x0087,
    SetDiffDamper = 0x0088,
    SetDiffDamperResponse = 0x0089,
    SetDiffTrim = 0x008A,
    SetDiffTrimResponse = 0x008B,
    SetDynamicsModel = 0x008C,
    SetDynamicsModelResponse = 0x008D,
}

impl MessageKind {
    pub fn from_u16(v: u16) -> Option<Self> {
        Some(match v {
            0x0001 => Self::Identify,
            0x0002 => Self::IdentifyResponse,
            0x0030 => Self::ConfigureAxes,
            0x0031 => Self::ConfigureAxesResponse,
            0x0040 => Self::QueryRuntimeCaps,
            0x0041 => Self::RuntimeCapsResponse,
            0x0042 => Self::ClaimHandshake,
            0x0043 => Self::ClaimHandshakeReply,
            0x0044 => Self::QueryMotorState,
            0x0045 => Self::MotorStateResponse,
            0x0060 => Self::PushPieces,
            0x0061 => Self::PushPiecesResponse,
            0x0068 => Self::StartCapture,
            0x0069 => Self::StartCaptureResponse,
            0x006A => Self::StopCapture,
            0x006B => Self::StopCaptureResponse,
            0x006C => Self::ResonanceBuzz,
            0x006D => Self::ResonanceBuzzResponse,
            0x006E => Self::ArmSensorlessEndstop,
            0x006F => Self::ArmSensorlessEndstopResponse,
            0x0070 => Self::SetTorque,
            0x0071 => Self::SetTorqueResponse,
            0x0072 => Self::Stop,
            0x0073 => Self::StopResponse,
            0x0074 => Self::SetDriveLimits,
            0x0075 => Self::SetDriveLimitsResponse,
            0x0076 => Self::RestoreDriveLimits,
            0x0077 => Self::RestoreDriveLimitsResponse,
            0x0078 => Self::ResumeStream,
            0x0079 => Self::ResumeStreamResponse,
            0x007A => Self::SeedServoHome,
            0x007B => Self::SeedServoHomeResponse,
            0x007C => Self::SdoRead,
            0x007D => Self::SdoReadResponse,
            0x007E => Self::SdoWrite,
            0x007F => Self::SdoWriteResponse,
            0x0082 => Self::FaultEvent,
            0x0083 => Self::StatusHeartbeat,
            0x0084 => Self::McuLog,
            0x0085 => Self::EndstopTrip,
            0x0086 => Self::SetStrainComp,
            0x0087 => Self::SetStrainCompResponse,
            0x0088 => Self::SetDiffDamper,
            0x0089 => Self::SetDiffDamperResponse,
            0x008A => Self::SetDiffTrim,
            0x008B => Self::SetDiffTrimResponse,
            0x008C => Self::SetDynamicsModel,
            0x008D => Self::SetDynamicsModelResponse,
            _ => return None,
        })
    }

    pub fn as_u16(self) -> u16 {
        self as u16
    }

    pub fn is_schema_validated(self) -> bool {
        !matches!(self, Self::Identify | Self::IdentifyResponse)
    }

    pub fn is_event(self) -> bool {
        let tag = self as u16;
        (0x0080..=0x00BF).contains(&tag)
    }
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub struct ConfigureAxes {
    pub kinematics: u8,
    pub present_mask: u8,
    pub awd_mask: u8,
    pub invert_mask: u8,
    pub steps_per_mm: [f32; 4],
}

impl Encode for ConfigureAxes {
    fn encode(&self, out: &mut Vec<u8>) {
        put_u8(out, self.kinematics);
        put_u8(out, self.present_mask);
        put_u8(out, self.awd_mask);
        put_u8(out, self.invert_mask);
        for v in &self.steps_per_mm {
            put_f32(out, *v);
        }
    }
}

impl Decode for ConfigureAxes {
    fn decode_from(c: &mut Cursor<'_>) -> Result<Self, DecodeError> {
        Ok(Self {
            kinematics: get_u8(c)?,
            present_mask: get_u8(c)?,
            awd_mask: get_u8(c)?,
            invert_mask: get_u8(c)?,
            steps_per_mm: [get_f32(c)?, get_f32(c)?, get_f32(c)?, get_f32(c)?],
        })
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ConfigureAxesResponse {
    pub result: i32,
}

impl Encode for ConfigureAxesResponse {
    fn encode(&self, out: &mut Vec<u8>) {
        put_i32(out, self.result);
    }
}

impl Decode for ConfigureAxesResponse {
    fn decode_from(c: &mut Cursor<'_>) -> Result<Self, DecodeError> {
        Ok(Self {
            result: get_i32(c)?,
        })
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct QueryRuntimeCaps;

impl Encode for QueryRuntimeCaps {
    fn encode(&self, _out: &mut Vec<u8>) {}
}

impl Decode for QueryRuntimeCaps {
    fn decode_from(_c: &mut Cursor<'_>) -> Result<Self, DecodeError> {
        Ok(Self)
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RuntimeCapsResponse {
    pub total_piece_memory: u32,
}

impl Encode for RuntimeCapsResponse {
    fn encode(&self, out: &mut Vec<u8>) {
        put_u32(out, self.total_piece_memory);
    }
}

impl Decode for RuntimeCapsResponse {
    fn decode_from(c: &mut Cursor<'_>) -> Result<Self, DecodeError> {
        Ok(Self {
            total_piece_memory: get_u32(c)?,
        })
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ClaimHandshake;

impl Encode for ClaimHandshake {
    fn encode(&self, _out: &mut Vec<u8>) {}
}

impl Decode for ClaimHandshake {
    fn decode_from(_c: &mut Cursor<'_>) -> Result<Self, DecodeError> {
        Ok(Self)
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct QueryMotorState;

impl Encode for QueryMotorState {
    fn encode(&self, _out: &mut Vec<u8>) {}
}

impl Decode for QueryMotorState {
    fn decode_from(_c: &mut Cursor<'_>) -> Result<Self, DecodeError> {
        Ok(Self)
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct StartCaptureResponse {
    pub result: i32,
}

impl Encode for StartCaptureResponse {
    fn encode(&self, out: &mut Vec<u8>) {
        put_i32(out, self.result);
    }
}

impl Decode for StartCaptureResponse {
    fn decode_from(c: &mut Cursor<'_>) -> Result<Self, DecodeError> {
        Ok(Self {
            result: get_i32(c)?,
        })
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct StopCapture;

impl Encode for StopCapture {
    fn encode(&self, _out: &mut Vec<u8>) {}
}

impl Decode for StopCapture {
    fn decode_from(_c: &mut Cursor<'_>) -> Result<Self, DecodeError> {
        Ok(Self)
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct StopCaptureResponse {
    pub result: i32,
    pub samples: u64,
    pub overflow_cycle: u64,
}

impl Encode for StopCaptureResponse {
    fn encode(&self, out: &mut Vec<u8>) {
        put_i32(out, self.result);
        put_u64(out, self.samples);
        put_u64(out, self.overflow_cycle);
    }
}

impl Decode for StopCaptureResponse {
    fn decode_from(c: &mut Cursor<'_>) -> Result<Self, DecodeError> {
        Ok(Self {
            result: get_i32(c)?,
            samples: get_u64(c)?,
            overflow_cycle: get_u64(c)?,
        })
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ResonanceBuzz {
    pub axis_mask: u8,
    pub sign_mask: u8,
    pub freq_start_millihz: u32,
    pub freq_end_millihz: u32,
    pub amplitude_nm: u32,
    pub duration_ms: u32,
    pub ramp_ms: u32,
}

impl Encode for ResonanceBuzz {
    fn encode(&self, out: &mut Vec<u8>) {
        put_u8(out, self.axis_mask);
        put_u8(out, self.sign_mask);
        put_u32(out, self.freq_start_millihz);
        put_u32(out, self.freq_end_millihz);
        put_u32(out, self.amplitude_nm);
        put_u32(out, self.duration_ms);
        put_u32(out, self.ramp_ms);
    }
}

impl Decode for ResonanceBuzz {
    fn decode_from(c: &mut Cursor<'_>) -> Result<Self, DecodeError> {
        Ok(Self {
            axis_mask: get_u8(c)?,
            sign_mask: get_u8(c)?,
            freq_start_millihz: get_u32(c)?,
            freq_end_millihz: get_u32(c)?,
            amplitude_nm: get_u32(c)?,
            duration_ms: get_u32(c)?,
            ramp_ms: get_u32(c)?,
        })
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ResonanceBuzzResponse {
    pub result: i32,
}

impl Encode for ResonanceBuzzResponse {
    fn encode(&self, out: &mut Vec<u8>) {
        put_i32(out, self.result);
    }
}

impl Decode for ResonanceBuzzResponse {
    fn decode_from(c: &mut Cursor<'_>) -> Result<Self, DecodeError> {
        Ok(Self {
            result: get_i32(c)?,
        })
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ArmSensorlessEndstop {
    pub slot: u8,
    pub endstop_id: u8,
    pub torque_trip_tenth_pct: u16,
    pub enable: u8,
}

impl Encode for ArmSensorlessEndstop {
    fn encode(&self, out: &mut Vec<u8>) {
        put_u8(out, self.slot);
        put_u8(out, self.endstop_id);
        put_u16(out, self.torque_trip_tenth_pct);
        put_u8(out, self.enable);
    }
}

impl Decode for ArmSensorlessEndstop {
    fn decode_from(c: &mut Cursor<'_>) -> Result<Self, DecodeError> {
        Ok(Self {
            slot: get_u8(c)?,
            endstop_id: get_u8(c)?,
            torque_trip_tenth_pct: get_u16(c)?,
            enable: get_u8(c)?,
        })
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ArmSensorlessEndstopResponse {
    pub result: i32,
}

impl Encode for ArmSensorlessEndstopResponse {
    fn encode(&self, out: &mut Vec<u8>) {
        put_i32(out, self.result);
    }
}

impl Decode for ArmSensorlessEndstopResponse {
    fn decode_from(c: &mut Cursor<'_>) -> Result<Self, DecodeError> {
        Ok(Self {
            result: get_i32(c)?,
        })
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SetTorque {
    pub value: u8,
    pub execute_at_ns: u64,
}

impl Encode for SetTorque {
    fn encode(&self, out: &mut Vec<u8>) {
        put_u8(out, self.value);
        put_u64(out, self.execute_at_ns);
    }
}

impl Decode for SetTorque {
    fn decode_from(c: &mut Cursor<'_>) -> Result<Self, DecodeError> {
        Ok(Self {
            value: get_u8(c)?,
            execute_at_ns: get_u64(c)?,
        })
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SetTorqueResponse {
    pub result: i32,
}

impl Encode for SetTorqueResponse {
    fn encode(&self, out: &mut Vec<u8>) {
        put_i32(out, self.result);
    }
}

impl Decode for SetTorqueResponse {
    fn decode_from(c: &mut Cursor<'_>) -> Result<Self, DecodeError> {
        Ok(Self {
            result: get_i32(c)?,
        })
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Stop;

impl Encode for Stop {
    fn encode(&self, _out: &mut Vec<u8>) {}
}

impl Decode for Stop {
    fn decode_from(_c: &mut Cursor<'_>) -> Result<Self, DecodeError> {
        Ok(Self)
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct StopResponse {
    pub result: i32,
    pub discard_clock: u64,
}

impl Encode for StopResponse {
    fn encode(&self, out: &mut Vec<u8>) {
        put_i32(out, self.result);
        put_u64(out, self.discard_clock);
    }
}

impl Decode for StopResponse {
    fn decode_from(c: &mut Cursor<'_>) -> Result<Self, DecodeError> {
        Ok(Self {
            result: get_i32(c)?,
            discard_clock: get_u64(c)?,
        })
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SetDriveLimits {
    pub slot: u8,
    pub following_error_counts: u32,
    pub max_torque_tenth_pct: u16,
}

impl Encode for SetDriveLimits {
    fn encode(&self, out: &mut Vec<u8>) {
        put_u8(out, self.slot);
        put_u32(out, self.following_error_counts);
        put_u16(out, self.max_torque_tenth_pct);
    }
}

impl Decode for SetDriveLimits {
    fn decode_from(c: &mut Cursor<'_>) -> Result<Self, DecodeError> {
        Ok(Self {
            slot: get_u8(c)?,
            following_error_counts: get_u32(c)?,
            max_torque_tenth_pct: get_u16(c)?,
        })
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SetDriveLimitsResponse {
    pub result: i32,
}

impl Encode for SetDriveLimitsResponse {
    fn encode(&self, out: &mut Vec<u8>) {
        put_i32(out, self.result);
    }
}

impl Decode for SetDriveLimitsResponse {
    fn decode_from(c: &mut Cursor<'_>) -> Result<Self, DecodeError> {
        Ok(Self {
            result: get_i32(c)?,
        })
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RestoreDriveLimits {
    pub slot: u8,
}

impl Encode for RestoreDriveLimits {
    fn encode(&self, out: &mut Vec<u8>) {
        put_u8(out, self.slot);
    }
}

impl Decode for RestoreDriveLimits {
    fn decode_from(c: &mut Cursor<'_>) -> Result<Self, DecodeError> {
        Ok(Self { slot: get_u8(c)? })
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RestoreDriveLimitsResponse {
    pub result: i32,
}

impl Encode for RestoreDriveLimitsResponse {
    fn encode(&self, out: &mut Vec<u8>) {
        put_i32(out, self.result);
    }
}

impl Decode for RestoreDriveLimitsResponse {
    fn decode_from(c: &mut Cursor<'_>) -> Result<Self, DecodeError> {
        Ok(Self {
            result: get_i32(c)?,
        })
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ResumeStream;

impl Encode for ResumeStream {
    fn encode(&self, _out: &mut Vec<u8>) {}
}

impl Decode for ResumeStream {
    fn decode_from(_c: &mut Cursor<'_>) -> Result<Self, DecodeError> {
        Ok(Self)
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ResumeStreamResponse {
    pub result: i32,
}

impl Encode for ResumeStreamResponse {
    fn encode(&self, out: &mut Vec<u8>) {
        put_i32(out, self.result);
    }
}

impl Decode for ResumeStreamResponse {
    fn decode_from(c: &mut Cursor<'_>) -> Result<Self, DecodeError> {
        Ok(Self {
            result: get_i32(c)?,
        })
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SeedServoHome {
    pub slot: u8,
    pub home_q16: i32,
}

impl Encode for SeedServoHome {
    fn encode(&self, out: &mut Vec<u8>) {
        put_u8(out, self.slot);
        put_i32(out, self.home_q16);
    }
}

impl Decode for SeedServoHome {
    fn decode_from(c: &mut Cursor<'_>) -> Result<Self, DecodeError> {
        Ok(Self {
            slot: get_u8(c)?,
            home_q16: get_i32(c)?,
        })
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SeedServoHomeResponse {
    pub result: i32,
}

impl Encode for SeedServoHomeResponse {
    fn encode(&self, out: &mut Vec<u8>) {
        put_i32(out, self.result);
    }
}

impl Decode for SeedServoHomeResponse {
    fn decode_from(c: &mut Cursor<'_>) -> Result<Self, DecodeError> {
        Ok(Self {
            result: get_i32(c)?,
        })
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SdoRead {
    pub slot: u8,
    pub index: u16,
    pub subindex: u8,
}

impl Encode for SdoRead {
    fn encode(&self, out: &mut Vec<u8>) {
        put_u8(out, self.slot);
        put_u16(out, self.index);
        put_u8(out, self.subindex);
    }
}

impl Decode for SdoRead {
    fn decode_from(c: &mut Cursor<'_>) -> Result<Self, DecodeError> {
        Ok(Self {
            slot: get_u8(c)?,
            index: get_u16(c)?,
            subindex: get_u8(c)?,
        })
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SdoReadResponse {
    pub result: i32,
    pub size: u8,
    pub data: [u8; 4],
}

impl Encode for SdoReadResponse {
    fn encode(&self, out: &mut Vec<u8>) {
        put_i32(out, self.result);
        put_u8(out, self.size);
        out.extend_from_slice(&self.data);
    }
}

impl Decode for SdoReadResponse {
    fn decode_from(c: &mut Cursor<'_>) -> Result<Self, DecodeError> {
        Ok(Self {
            result: get_i32(c)?,
            size: get_u8(c)?,
            data: [get_u8(c)?, get_u8(c)?, get_u8(c)?, get_u8(c)?],
        })
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SdoWrite {
    pub slot: u8,
    pub index: u16,
    pub subindex: u8,
    pub size: u8,
    pub value: i64,
}

impl Encode for SdoWrite {
    fn encode(&self, out: &mut Vec<u8>) {
        put_u8(out, self.slot);
        put_u16(out, self.index);
        put_u8(out, self.subindex);
        put_u8(out, self.size);
        put_u64(out, self.value as u64);
    }
}

impl Decode for SdoWrite {
    fn decode_from(c: &mut Cursor<'_>) -> Result<Self, DecodeError> {
        Ok(Self {
            slot: get_u8(c)?,
            index: get_u16(c)?,
            subindex: get_u8(c)?,
            size: get_u8(c)?,
            value: get_u64(c)? as i64,
        })
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SdoWriteResponse {
    pub result: i32,
    pub readback_size: u8,
    pub readback_data: [u8; 4],
}

impl Encode for SdoWriteResponse {
    fn encode(&self, out: &mut Vec<u8>) {
        put_i32(out, self.result);
        put_u8(out, self.readback_size);
        out.extend_from_slice(&self.readback_data);
    }
}

impl Decode for SdoWriteResponse {
    fn decode_from(c: &mut Cursor<'_>) -> Result<Self, DecodeError> {
        Ok(Self {
            result: get_i32(c)?,
            readback_size: get_u8(c)?,
            readback_data: [get_u8(c)?, get_u8(c)?, get_u8(c)?, get_u8(c)?],
        })
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct FaultEvent {
    pub fault_code: u16,
    pub fault_detail: u32,
    pub segment_id: u32,
}

impl Encode for FaultEvent {
    fn encode(&self, out: &mut Vec<u8>) {
        put_u16(out, self.fault_code);
        put_u32(out, self.fault_detail);
        put_u32(out, self.segment_id);
    }
}

impl Decode for FaultEvent {
    fn decode_from(c: &mut Cursor<'_>) -> Result<Self, DecodeError> {
        Ok(Self {
            fault_code: get_u16(c)?,
            fault_detail: get_u32(c)?,
            segment_id: get_u32(c)?,
        })
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct McuLog {
    pub mcu_tick: u64,
    pub level: u8,
    pub subsystem: u8,
    pub event: u16,
    pub code: u16,
    pub seq: u16,
    pub args: [u32; 2],
}

impl Encode for McuLog {
    fn encode(&self, out: &mut Vec<u8>) {
        put_u64(out, self.mcu_tick);
        put_u8(out, self.level);
        put_u8(out, self.subsystem);
        put_u16(out, self.event);
        put_u16(out, self.code);
        put_u16(out, self.seq);
        for v in &self.args {
            put_u32(out, *v);
        }
    }
}

impl Decode for McuLog {
    fn decode_from(c: &mut Cursor<'_>) -> Result<Self, DecodeError> {
        Ok(Self {
            mcu_tick: get_u64(c)?,
            level: get_u8(c)?,
            subsystem: get_u8(c)?,
            event: get_u16(c)?,
            code: get_u16(c)?,
            seq: get_u16(c)?,
            args: [get_u32(c)?, get_u32(c)?],
        })
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct EndstopTrip {
    pub endstop_id: u8,
    pub trip_clock: u64,
}

impl Encode for EndstopTrip {
    fn encode(&self, out: &mut Vec<u8>) {
        put_u8(out, self.endstop_id);
        put_u64(out, self.trip_clock);
    }
}

impl Decode for EndstopTrip {
    fn decode_from(c: &mut Cursor<'_>) -> Result<Self, DecodeError> {
        Ok(Self {
            endstop_id: get_u8(c)?,
            trip_clock: get_u64(c)?,
        })
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SetStrainCompResponse {
    pub result: i32,
}

impl Encode for SetStrainCompResponse {
    fn encode(&self, out: &mut Vec<u8>) {
        put_i32(out, self.result);
    }
}

impl Decode for SetStrainCompResponse {
    fn decode_from(c: &mut Cursor<'_>) -> Result<Self, DecodeError> {
        Ok(Self {
            result: get_i32(c)?,
        })
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SetDiffDamper {
    pub slot_a: u8,
    pub slot_b: u8,
    pub gain_milli: u32,
    pub clamp_tenths: u16,
    pub lpf_millihz: u32,
    pub lead_us: u16,
}

impl Encode for SetDiffDamper {
    fn encode(&self, out: &mut Vec<u8>) {
        put_u8(out, self.slot_a);
        put_u8(out, self.slot_b);
        put_u32(out, self.gain_milli);
        put_u16(out, self.clamp_tenths);
        put_u32(out, self.lpf_millihz);
        put_u16(out, self.lead_us);
    }
}

impl Decode for SetDiffDamper {
    fn decode_from(c: &mut Cursor<'_>) -> Result<Self, DecodeError> {
        Ok(Self {
            slot_a: get_u8(c)?,
            slot_b: get_u8(c)?,
            gain_milli: get_u32(c)?,
            clamp_tenths: get_u16(c)?,
            lpf_millihz: get_u32(c)?,
            lead_us: get_u16(c)?,
        })
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SetDiffDamperResponse {
    pub result: i32,
}

impl Encode for SetDiffDamperResponse {
    fn encode(&self, out: &mut Vec<u8>) {
        put_i32(out, self.result);
    }
}

impl Decode for SetDiffDamperResponse {
    fn decode_from(c: &mut Cursor<'_>) -> Result<Self, DecodeError> {
        Ok(Self {
            result: get_i32(c)?,
        })
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SetDiffTrim {
    pub slot_a: u8,
    pub slot_b: u8,
    pub gain_micro: u32,
    pub clamp_um: u16,
    pub lpf_millihz: u32,
}

impl Encode for SetDiffTrim {
    fn encode(&self, out: &mut Vec<u8>) {
        put_u8(out, self.slot_a);
        put_u8(out, self.slot_b);
        put_u32(out, self.gain_micro);
        put_u16(out, self.clamp_um);
        put_u32(out, self.lpf_millihz);
    }
}

impl Decode for SetDiffTrim {
    fn decode_from(c: &mut Cursor<'_>) -> Result<Self, DecodeError> {
        Ok(Self {
            slot_a: get_u8(c)?,
            slot_b: get_u8(c)?,
            gain_micro: get_u32(c)?,
            clamp_um: get_u16(c)?,
            lpf_millihz: get_u32(c)?,
        })
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SetDiffTrimResponse {
    pub result: i32,
}

impl Encode for SetDiffTrimResponse {
    fn encode(&self, out: &mut Vec<u8>) {
        put_i32(out, self.result);
    }
}

impl Decode for SetDiffTrimResponse {
    fn decode_from(c: &mut Cursor<'_>) -> Result<Self, DecodeError> {
        Ok(Self {
            result: get_i32(c)?,
        })
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SetDynamicsModelResponse {
    pub result: i32,
}

impl Encode for SetDynamicsModelResponse {
    fn encode(&self, out: &mut Vec<u8>) {
        put_i32(out, self.result);
    }
}

impl Decode for SetDynamicsModelResponse {
    fn decode_from(c: &mut Cursor<'_>) -> Result<Self, DecodeError> {
        Ok(Self {
            result: get_i32(c)?,
        })
    }
}
