use super::*;

#[test]
fn matches_orca_layer_change() {
    assert_eq!(
        match_comment(";LAYER:5"),
        Some(MarkerKind::LayerChange { layer: Some(5) })
    );
    assert_eq!(
        match_comment(";LAYER:0"),
        Some(MarkerKind::LayerChange { layer: Some(0) })
    );
    assert_eq!(
        match_comment(";LAYER_CHANGE"),
        Some(MarkerKind::LayerChange { layer: None })
    );
}

#[test]
fn matches_prusa_layer() {
    assert_eq!(
        match_comment(";LAYER:12"),
        Some(MarkerKind::LayerChange { layer: Some(12) })
    );
}

#[test]
fn matches_type() {
    assert_eq!(
        match_comment(";TYPE:WALL-OUTER"),
        Some(MarkerKind::LayerType {
            name: "WALL-OUTER".to_string().into_boxed_str()
        })
    );
}

#[test]
fn unknown_comment_returns_none() {
    assert_eq!(match_comment("; just a comment"), None);
    assert_eq!(match_comment(";generated by Slic3r"), None);
}
