use sha2::{Digest, Sha256};
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

include!("schema_def.rs");

const PROTO_VERSION: u8 = 0x01;

fn main() {
    println!("cargo:rerun-if-changed=schema_def.rs");
    println!("cargo:rerun-if-changed=build.rs");
    // Self-healing: a hand edit to the generated file triggers a rebuild,
    // which overwrites it with the schema-derived truth.
    println!("cargo:rerun-if-changed=src/messages/generated.rs");

    assert_ascending_tags(SCHEMA_MESSAGES);

    let canonical = canonicalize_schema(SCHEMA_MESSAGES);
    let mut hasher = Sha256::new();
    hasher.update(canonical.as_bytes());
    let hash: [u8; 32] = hasher.finalize().into();

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR not set"));
    let mut rs = String::new();
    rs.push_str("// Generated by build.rs. Do not edit.\n");
    rs.push_str("pub const SCHEMA_HASH: [u8; 32] = [");
    for (i, b) in hash.iter().enumerate() {
        if i > 0 {
            rs.push_str(", ");
        }
        rs.push_str(&format!("0x{b:02x}"));
    }
    rs.push_str("];\n");
    rs.push_str(&format!(
        "pub const SCHEMA_HASH_HEX: &str = \"{}\";\n",
        hex_string(&hash)
    ));
    rs.push_str("pub const SCHEMA_CANONICAL: &str = ");
    rs.push_str(&rust_string_literal(&canonical));
    rs.push_str(";\n");
    fs::write(out_dir.join("schema_hash.rs"), rs).expect("write schema_hash.rs");

    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set"));

    write_if_changed(
        &manifest_dir
            .join("src")
            .join("messages")
            .join("generated.rs"),
        &generate_messages(),
    );

    let header_path = manifest_dir
        .join("..")
        .join("..")
        .join("src")
        .join("mcu_protocol_schema.h");

    let mut h = String::new();
    h.push_str("/* Generated by rust/mcu-protocol/build.rs. Do not edit. */\n");
    h.push_str("#ifndef MCU_PROTOCOL_SCHEMA_H\n");
    h.push_str("#define MCU_PROTOCOL_SCHEMA_H\n\n");
    h.push_str("#include <stdint.h>\n\n");
    h.push_str(&format!(
        "#define MCU_PROTO_VERSION 0x{PROTO_VERSION:02x}\n\n"
    ));

    h.push_str("/* Bootstrap message type tags (fixed-layout per spec §5). */\n");
    for (tag, name) in BOOTSTRAP_TAGS {
        h.push_str(&format!(
            "#define MCU_MSG_{} 0x{:04x}\n",
            upper_snake(name),
            tag
        ));
    }
    h.push('\n');

    h.push_str("/* Schema-validated message type tags. */\n");
    for m in SCHEMA_MESSAGES {
        h.push_str(&format!(
            "#define MCU_MSG_{} 0x{:04x}\n",
            upper_snake(m.name),
            m.type_tag
        ));
    }
    h.push('\n');

    h.push_str("/* Piece wire/ring geometry (single source of truth for C). */\n");
    h.push_str("#define MCU_PIECE_MAX_COEFFS 8\n");
    h.push_str("#define MCU_PIECE_WIRE_HEADER_LEN 16\n");
    h.push_str("#define MCU_PIECE_SLOT_LEN 48\n\n");

    h.push_str("/* SHA-256 over canonicalized schema (excludes bootstrap). */\n");
    h.push_str("static const uint8_t MCU_SCHEMA_HASH[32] = {\n    ");
    for (i, b) in hash.iter().enumerate() {
        if i > 0 {
            h.push_str(", ");
            if i % 8 == 0 {
                h.push_str("\n    ");
            }
        }
        h.push_str(&format!("0x{b:02x}"));
    }
    h.push_str("\n};\n\n");

    h.push_str("#endif /* MCU_PROTOCOL_SCHEMA_H */\n");

    // Guard: skip header generation only when `src/` doesn't exist at all —
    // that is the standalone-crate-publish path where the firmware tree is
    // absent. Any other failure (disk full, permissions, …) is a hard error:
    // a silently stale C header violates the deploy-lockstep guarantee.
    if let Some(parent) = header_path.parent() {
        if !parent.exists() {
            println!(
                "cargo:warning=mcu-protocol: skipping C header generation; {} does not exist \
                 (standalone-crate-publish path — expected)",
                parent.display()
            );
            return;
        }
    }
    fs::write(&header_path, h).unwrap_or_else(|e| {
        panic!(
            "mcu-protocol build.rs: failed to write C header {}: {e}\n\
             (src/ exists but write failed — disk full, permissions issue, or path wrong)",
            header_path.display()
        )
    });
}

fn assert_ascending_tags(messages: &[SchemaMessage]) {
    for pair in messages.windows(2) {
        assert!(
            pair[0].type_tag < pair[1].type_tag,
            "SCHEMA_MESSAGES must be sorted by ascending type_tag: 0x{:04x} before 0x{:04x}",
            pair[0].type_tag,
            pair[1].type_tag
        );
    }
}

/// Write only when contents differ, so no-op builds keep the file's mtime
/// stable and cargo's fingerprint converges instead of rebuilding forever.
fn write_if_changed(path: &Path, contents: &str) {
    if fs::read_to_string(path).is_ok_and(|current| current == contents) {
        return;
    }
    fs::write(path, contents).unwrap_or_else(|e| {
        panic!(
            "mcu-protocol build.rs: failed to write generated codec {}: {e}",
            path.display()
        )
    });
}

// ---------------------------------------------------------------------------
// Codec generation
// ---------------------------------------------------------------------------

const SCALARS: &[&str] = &["u8", "u16", "u32", "u64", "i32", "i64", "f32"];

enum FieldRepr {
    Scalar(&'static str),
    FixedArray(&'static str, usize),
}

/// `None` means the field (and thus its whole message) keeps a hand-written
/// codec in `src/messages.rs`.
fn field_repr(ty: &str) -> Option<FieldRepr> {
    if ty == "string" || ty.starts_with("array<") {
        return None;
    }
    if let Some((base, rest)) = ty.split_once('[') {
        let n: usize = rest
            .strip_suffix(']')
            .and_then(|s| s.parse().ok())
            .unwrap_or_else(|| panic!("malformed fixed-array field type: {ty}"));
        let base = scalar_name(base, ty);
        assert!(
            n <= 4,
            "field type {ty}: teach the generator to line-wrap arrays longer than 4"
        );
        return Some(FieldRepr::FixedArray(base, n));
    }
    Some(FieldRepr::Scalar(scalar_name(ty, ty)))
}

fn scalar_name(base: &str, full_ty: &str) -> &'static str {
    SCALARS
        .iter()
        .find(|s| **s == base)
        .unwrap_or_else(|| panic!("unknown scalar in field type: {full_ty}"))
}

fn message_is_generated(m: &SchemaMessage) -> bool {
    m.fields.iter().all(|f| field_repr(f.ty).is_some())
}

fn generate_messages() -> String {
    let mut out = String::new();
    out.push_str(
        "// @generated by mcu-protocol/build.rs from schema_def.rs — DO NOT EDIT.\n\
         // Regenerated on every build; hand edits are overwritten.\n\n",
    );
    for import in codec_imports() {
        out.push_str(&format!("use crate::codec::{import};\n"));
    }
    out.push('\n');
    out.push_str(&generate_message_kind());
    for m in SCHEMA_MESSAGES.iter().filter(|m| message_is_generated(m)) {
        out.push('\n');
        out.push_str(&generate_struct(m));
        out.push('\n');
        out.push_str(&generate_encode(m));
        out.push('\n');
        out.push_str(&generate_decode(m));
    }
    out
}

fn codec_imports() -> Vec<String> {
    let mut gets: Vec<&str> = Vec::new();
    let mut puts: Vec<&str> = Vec::new();
    for m in SCHEMA_MESSAGES.iter().filter(|m| message_is_generated(m)) {
        for f in m.fields {
            match field_repr(f.ty).expect("generated message field") {
                // i64 rides the wire via the u64 helpers.
                FieldRepr::Scalar("i64") => {
                    gets.push("u64");
                    puts.push("u64");
                }
                FieldRepr::Scalar(s) => {
                    gets.push(s);
                    puts.push(s);
                }
                // u8 arrays decode per-element but encode via extend_from_slice.
                FieldRepr::FixedArray("u8", _) => gets.push("u8"),
                FieldRepr::FixedArray(s, _) => {
                    gets.push(s);
                    puts.push(s);
                }
            }
        }
    }
    // rustfmt orders use statements version-sorted; match it so the emitted
    // file is a rustfmt fixed point.
    const IMPORT_ORDER: &[&str] = &["f32", "i32", "i64", "u8", "u16", "u32", "u64"];
    fn ordered(mut v: Vec<&'static str>) -> Vec<&'static str> {
        v.sort_by_key(|s| IMPORT_ORDER.iter().position(|k| k == s));
        v.dedup();
        v
    }

    let mut imports: Vec<String> = ["Cursor", "Decode", "DecodeError", "Encode"]
        .map(String::from)
        .to_vec();
    imports.extend(ordered(gets).iter().map(|s| format!("get_{s}")));
    imports.extend(ordered(puts).iter().map(|s| format!("put_{s}")));
    imports
}

fn generate_message_kind() -> String {
    let mut all: Vec<(u16, &str)> = BOOTSTRAP_TAGS.to_vec();
    all.extend(SCHEMA_MESSAGES.iter().map(|m| (m.type_tag, m.name)));

    let mut s = String::new();
    s.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    s.push_str("#[repr(u16)]\n");
    s.push_str("pub enum MessageKind {\n");
    for (tag, name) in &all {
        s.push_str(&format!("    {name} = 0x{tag:04X},\n"));
    }
    s.push_str("}\n\n");

    s.push_str("impl MessageKind {\n");
    s.push_str("    pub fn from_u16(v: u16) -> Option<Self> {\n");
    s.push_str("        Some(match v {\n");
    for (tag, name) in &all {
        s.push_str(&format!("            0x{tag:04X} => Self::{name},\n"));
    }
    s.push_str("            _ => return None,\n");
    s.push_str("        })\n");
    s.push_str("    }\n\n");
    s.push_str("    pub fn as_u16(self) -> u16 {\n");
    s.push_str("        self as u16\n");
    s.push_str("    }\n\n");
    let bootstrap_pattern = BOOTSTRAP_TAGS
        .iter()
        .map(|(_, name)| format!("Self::{name}"))
        .collect::<Vec<_>>()
        .join(" | ");
    s.push_str("    pub fn is_schema_validated(self) -> bool {\n");
    s.push_str(&format!("        !matches!(self, {bootstrap_pattern})\n"));
    s.push_str("    }\n\n");
    s.push_str("    pub fn is_event(self) -> bool {\n");
    s.push_str("        let tag = self as u16;\n");
    s.push_str("        (0x0080..=0x00BF).contains(&tag)\n");
    s.push_str("    }\n");
    s.push_str("}\n");
    s
}

fn rust_field_type(repr: &FieldRepr) -> String {
    match repr {
        FieldRepr::Scalar(s) => (*s).to_string(),
        FieldRepr::FixedArray(s, n) => format!("[{s}; {n}]"),
    }
}

fn generate_struct(m: &SchemaMessage) -> String {
    let has_f32 = m.fields.iter().any(|f| {
        matches!(
            field_repr(f.ty).expect("generated message field"),
            FieldRepr::Scalar("f32") | FieldRepr::FixedArray("f32", _)
        )
    });
    let eq = if has_f32 { "" } else { ", Eq" };
    let mut s = String::new();
    s.push_str(&format!("#[derive(Debug, Clone, Copy, PartialEq{eq})]\n"));
    if m.fields.is_empty() {
        s.push_str(&format!("pub struct {};\n", m.name));
        return s;
    }
    s.push_str(&format!("pub struct {} {{\n", m.name));
    for f in m.fields {
        let repr = field_repr(f.ty).expect("generated message field");
        s.push_str(&format!(
            "    pub {}: {},\n",
            f.name,
            rust_field_type(&repr)
        ));
    }
    s.push_str("}\n");
    s
}

fn generate_encode(m: &SchemaMessage) -> String {
    let mut s = String::new();
    s.push_str(&format!("impl Encode for {} {{\n", m.name));
    if m.fields.is_empty() {
        s.push_str("    fn encode(&self, _out: &mut Vec<u8>) {}\n");
        s.push_str("}\n");
        return s;
    }
    s.push_str("    fn encode(&self, out: &mut Vec<u8>) {\n");
    for f in m.fields {
        match field_repr(f.ty).expect("generated message field") {
            FieldRepr::Scalar("i64") => {
                s.push_str(&format!("        put_u64(out, self.{} as u64);\n", f.name));
            }
            FieldRepr::Scalar(base) => {
                s.push_str(&format!("        put_{base}(out, self.{});\n", f.name));
            }
            FieldRepr::FixedArray("u8", _) => {
                s.push_str(&format!(
                    "        out.extend_from_slice(&self.{});\n",
                    f.name
                ));
            }
            FieldRepr::FixedArray(base, _) => {
                s.push_str(&format!("        for v in &self.{} {{\n", f.name));
                s.push_str(&format!("            put_{base}(out, *v);\n"));
                s.push_str("        }\n");
            }
        }
    }
    s.push_str("    }\n");
    s.push_str("}\n");
    s
}

fn generate_decode(m: &SchemaMessage) -> String {
    let mut s = String::new();
    s.push_str(&format!("impl Decode for {} {{\n", m.name));
    if m.fields.is_empty() {
        s.push_str("    fn decode_from(_c: &mut Cursor<'_>) -> Result<Self, DecodeError> {\n");
        s.push_str("        Ok(Self)\n");
        s.push_str("    }\n");
        s.push_str("}\n");
        return s;
    }
    s.push_str("    fn decode_from(c: &mut Cursor<'_>) -> Result<Self, DecodeError> {\n");
    let field_exprs: Vec<String> = m
        .fields
        .iter()
        .map(|f| {
            let expr = match field_repr(f.ty).expect("generated message field") {
                FieldRepr::Scalar("i64") => "get_u64(c)? as i64".to_string(),
                FieldRepr::Scalar(base) => format!("get_{base}(c)?"),
                FieldRepr::FixedArray(base, n) => {
                    let elems = vec![format!("get_{base}(c)?"); n].join(", ");
                    format!("[{elems}]")
                }
            };
            format!("{}: {expr}", f.name)
        })
        .collect();
    // rustfmt collapses struct literals whose body fits struct_lit_width (18).
    let body = field_exprs.join(", ");
    if body.len() <= 18 {
        s.push_str(&format!("        Ok(Self {{ {body} }})\n"));
    } else {
        s.push_str("        Ok(Self {\n");
        for fe in &field_exprs {
            s.push_str(&format!("            {fe},\n"));
        }
        s.push_str("        })\n");
    }
    s.push_str("    }\n");
    s.push_str("}\n");
    s
}

fn upper_snake(name: &str) -> String {
    let mut out = String::new();
    for (i, ch) in name.chars().enumerate() {
        if ch.is_ascii_uppercase() && i > 0 {
            out.push('_');
        }
        out.push(ch.to_ascii_uppercase());
    }
    out
}

fn hex_string(bytes: &[u8]) -> String {
    let mut s = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        s.push_str(&format!("{b:02x}"));
    }
    s
}

fn rust_string_literal(s: &str) -> String {
    let mut out = String::from("\"");
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}
