/*
* nurbs.h — generated by cbindgen.
* DO NOT EDIT. Regenerate via `cargo run -p c-api --bin gen-headers`.
* See docs/superpowers/specs/2026-04-26-nurbs-evaluation-library-design.md.
*/


#ifndef NURBS_H
#define NURBS_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct nurbs_ArcLengthTableRef_f32 nurbs_ArcLengthTableRef_f32;

typedef struct nurbs_ScalarNurbsRef_f32 nurbs_ScalarNurbsRef_f32;

typedef struct nurbs_VectorNurbsRef_f32__3 nurbs_VectorNurbsRef_f32__3;

extern void event_log_emit(uint8_t level,
                           uint8_t subsystem,
                           uint16_t event,
                           uint16_t code,
                           uint32_t arg0,
                           uint32_t arg1);

float nurbs_eval_f32(const struct nurbs_ScalarNurbsRef_f32 *curve, float u);

float nurbs_param_from_arc_length_f32(const struct nurbs_ArcLengthTableRef_f32 *table, float s);

void nurbs_vector_eval_3_f32(const struct nurbs_VectorNurbsRef_f32__3 *curve, float u, float *out);

int32_t runtime_bind_phase_motor(nurbs_Runtime *rt, uint8_t motor_idx, uint8_t slot_idx);

int32_t runtime_clock_sync_request(nurbs_Runtime *rt,
                                   uint32_t request_id,
                                   uint32_t host_send_time_lo,
                                   uint32_t host_send_time_hi,
                                   uint64_t *out_mcu_clock);

int32_t runtime_commit_head(nurbs_Runtime *rt, uint8_t axis_idx, uint32_t new_head);

int32_t runtime_configure_axis(nurbs_Runtime *rt,
                               uint8_t axis_idx,
                               uint8_t mode,
                               uint32_t microstep_distance_f32_bits,
                               uint16_t ring_depth,
                               const nurbs_StepperBindingRust *bindings_ptr,
                               uint8_t stepper_count);

int32_t runtime_discard_pending(nurbs_Runtime *rt);

uint32_t runtime_enqueue_success_lo(nurbs_Runtime *rt);

int32_t runtime_gate_pieces(nurbs_Runtime *rt);

double runtime_get_axis_accumulator(nurbs_Runtime *rt, uint8_t oid);

float runtime_get_axis_motor(nurbs_Runtime *rt, uint8_t oid);

uint32_t runtime_get_dispatcher_floor_cycles(void);

int32_t runtime_get_heartbeat(nurbs_Runtime *rt,
                              uint8_t *out_engine_state,
                              uint16_t *out_fault_code,
                              uint32_t *out_retired,
                              uintptr_t max_axes);

void runtime_get_last_timing(nurbs_Runtime *rt,
                             uint64_t *now_out,
                             uint64_t *t_start_out,
                             uint64_t *duration_out);

int32_t runtime_get_occupancy(nurbs_Runtime *rt, uint32_t *out_occupancy, uintptr_t max_axes);

int32_t runtime_get_phase_state(nurbs_Runtime *rt,
                                uint8_t stepper_oid,
                                uint8_t *out_axis_idx,
                                uint8_t *out_mode,
                                uint16_t *out_phase,
                                uint8_t *out_settled);

uint32_t runtime_get_sample_period_cycles(void);

uint8_t runtime_get_step_mode(nurbs_Runtime *rt, uint8_t stepper_idx);

int32_t runtime_get_stepper_count(nurbs_Runtime *rt, uint8_t oid);

uint32_t runtime_get_tick_counter(nurbs_Runtime *rt);

uint32_t runtime_get_xdirect_write_count(void);

int32_t runtime_handle_check_blob_version(const uint8_t *payload_ptr, uint32_t payload_len);

uint32_t runtime_handle_fault_detail(nurbs_Runtime *rt);

float runtime_handle_get_axis_steps_per_mm(nurbs_Runtime *rt, uint8_t oid);

uint32_t runtime_handle_last_modulated_duration_lo(nurbs_Runtime *rt);

uint32_t runtime_handle_last_modulated_elapsed_lo(nurbs_Runtime *rt);

uint32_t runtime_handle_last_retire_consumers_after_clear(nurbs_Runtime *rt);

uint32_t runtime_handle_modulated_retire_attempts(nurbs_Runtime *rt);

uint32_t runtime_handle_modulated_retire_successes(nurbs_Runtime *rt);

void runtime_handle_seed_widen(nurbs_Runtime *rt, uint64_t baseline_widened_clock);

uint32_t runtime_handle_tick_blocker(nurbs_Runtime *rt);

uint32_t runtime_handle_tick_blocker_exc(nurbs_Runtime *rt);

uint32_t runtime_handle_tick_blocker_pc(nurbs_Runtime *rt);

uint64_t runtime_handle_widened_now(nurbs_Runtime *rt);

int32_t runtime_install_step_queues(nurbs_Runtime *rt, uint8_t *queues);

uint32_t runtime_last_push_consumers_remaining(nurbs_Runtime *rt);

uint32_t runtime_last_push_x_handle(nurbs_Runtime *rt);

uint32_t runtime_last_push_y_handle(nurbs_Runtime *rt);

uint64_t runtime_now_ticks(nurbs_Runtime *rt);

int32_t runtime_phase_align_to(nurbs_Runtime *rt, uint8_t stepper_oid, uint16_t target_phase);

int32_t runtime_phase_jog_to(nurbs_Runtime *rt,
                             uint8_t stepper_oid,
                             uint16_t target_phase,
                             uint16_t max_microsteps_per_sample);

uint32_t runtime_push_seg_all_unused_lo(nurbs_Runtime *rt);

int32_t runtime_query_motor_state(nurbs_Runtime *rt,
                                  uint8_t *out_slots,
                                  int32_t *out_pos_q16,
                                  int32_t *out_vel_q16,
                                  uintptr_t max);

int32_t runtime_reset(nurbs_Runtime *rt);

int32_t runtime_seed_position(nurbs_Runtime *rt, int32_t x_q16, int32_t y_q16, int32_t z_q16);

int32_t runtime_set_axis_mode(nurbs_Runtime *rt, uint8_t axis_idx, uint8_t new_mode);

/**
 * Switch a phase-stepping handover group between Pulse and Phase. `oids`
 * points to `oid_len` stepper OIDs (the whole group); the MCU runs the
 * register dance locally. Foreground-only.
 */
int32_t runtime_set_axis_mode_group(nurbs_Runtime *rt,
                                    uint8_t axis_idx,
                                    uint8_t mode,
                                    const uint8_t *oids,
                                    uint8_t oid_len);

int32_t runtime_set_step_mode(nurbs_Runtime *rt,
                              uint8_t stepper_idx,
                              uint8_t mode,
                              uint8_t mcu_supports_phase);

int32_t runtime_set_stepper_offset(nurbs_Runtime *rt,
                                   uint8_t stepper_idx,
                                   int32_t delta_microsteps,
                                   uint16_t max_microsteps_per_sample);

int32_t runtime_stream_flush(nurbs_Runtime *rt, uint32_t *out_credit_epoch);

void runtime_tick_sample(nurbs_Runtime *rt);

int32_t runtime_ungate_pieces(nurbs_Runtime *rt);

int32_t runtime_write_piece(nurbs_Runtime *rt,
                            uint8_t axis_idx,
                            uint16_t start_slot,
                            uint8_t index,
                            const uint8_t *piece_ptr);

#endif  /* NURBS_H */
