/*
* runtime.h — generated by cbindgen.
* DO NOT EDIT. Regenerate via `cargo run -p c-api --bin gen-headers`.
* See docs/superpowers/specs/2026-04-28-layer-4-mcu-framework-stub-design.md.
*/


#ifndef RUNTIME_H
#define RUNTIME_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Per-axis additive contribution a buzz makes to one tick's dispatch inputs.
 */
typedef struct BuzzSample BuzzSample;

typedef struct Runtime {
  uint8_t _private[0];
} Runtime;

/**
 * Sentinel: `tmc_cs_oid == 0xFF` means "no TMC driver" (Pulse-only stepper).
 */
typedef struct StepperBindingRust {
  uint8_t stepper_oid;
  uint8_t tmc_cs_oid;
  uint8_t _pad[2];
} StepperBindingRust;



extern void event_log_emit(uint8_t level,
                           uint8_t subsystem,
                           uint16_t event,
                           uint16_t code,
                           uint32_t arg0,
                           uint32_t arg1);

int32_t runtime_bind_phase_motor(struct Runtime *rt, uint8_t motor_idx, uint8_t slot_idx);

int32_t runtime_clock_sync_request(struct Runtime *rt,
                                   uint32_t request_id,
                                   uint32_t host_send_time_lo,
                                   uint32_t host_send_time_hi,
                                   uint64_t *out_mcu_clock);

int32_t runtime_commit_head(struct Runtime *rt, uint8_t axis_idx, uint32_t new_head);

int32_t runtime_configure_axis(struct Runtime *rt,
                               uint8_t axis_idx,
                               uint8_t mode,
                               uint32_t microstep_distance_f32_bits,
                               uint16_t ring_depth,
                               const struct StepperBindingRust *bindings_ptr,
                               uint8_t stepper_count);

extern uint32_t runtime_cyccnt_read(void);

int32_t runtime_discard_pending(struct Runtime *rt);

uint32_t runtime_enqueue_success_lo(struct Runtime *rt);

int32_t runtime_gate_pieces(struct Runtime *rt);

double runtime_get_axis_accumulator(struct Runtime *rt, uint8_t oid);

float runtime_get_axis_motor(struct Runtime *rt, uint8_t oid);

uint32_t runtime_get_dispatcher_floor_cycles(void);

int32_t runtime_get_heartbeat(struct Runtime *rt,
                              uint8_t *out_engine_state,
                              uint16_t *out_fault_code,
                              uint32_t *out_retired,
                              uintptr_t max_axes);

void runtime_get_last_timing(struct Runtime *rt,
                             uint64_t *now_out,
                             uint64_t *t_start_out,
                             uint64_t *duration_out);

int32_t runtime_get_occupancy(struct Runtime *rt, uint32_t *out_occupancy, uintptr_t max_axes);

int32_t runtime_get_phase_state(struct Runtime *rt,
                                uint8_t stepper_oid,
                                uint8_t *out_axis_idx,
                                uint8_t *out_mode,
                                uint16_t *out_phase,
                                uint8_t *out_settled);

uint32_t runtime_get_sample_period_cycles(void);

uint8_t runtime_get_step_mode(struct Runtime *rt, uint8_t stepper_idx);

int32_t runtime_get_stepper_count(struct Runtime *rt, uint8_t oid);

uint32_t runtime_get_tick_counter(struct Runtime *rt);

uint32_t runtime_get_xdirect_write_count(void);

int32_t runtime_handle_check_blob_version(const uint8_t *payload_ptr, uint32_t payload_len);

struct Runtime *runtime_handle_create(void);

uint32_t runtime_handle_fault_detail(struct Runtime *rt);

float runtime_handle_get_axis_steps_per_mm(struct Runtime *rt, uint8_t oid);

int32_t runtime_handle_last_error(struct Runtime *rt);

uint32_t runtime_handle_last_modulated_duration_lo(struct Runtime *rt);

uint32_t runtime_handle_last_modulated_elapsed_lo(struct Runtime *rt);

uint32_t runtime_handle_last_retire_consumers_after_clear(struct Runtime *rt);

uint32_t runtime_handle_modulated_retire_attempts(struct Runtime *rt);

uint32_t runtime_handle_modulated_retire_successes(struct Runtime *rt);

void runtime_handle_seed_widen(struct Runtime *rt, uint64_t baseline_widened_clock);

uint8_t runtime_handle_status(struct Runtime *rt);

uint32_t runtime_handle_tick_blocker(struct Runtime *rt);

uint32_t runtime_handle_tick_blocker_exc(struct Runtime *rt);

uint32_t runtime_handle_tick_blocker_pc(struct Runtime *rt);

uint32_t runtime_handle_tick_counter(struct Runtime *rt);

uint64_t runtime_handle_widened_now(struct Runtime *rt);

int32_t runtime_install_step_queues(struct Runtime *rt, uint8_t *queues);

uint32_t runtime_last_push_consumers_remaining(struct Runtime *rt);

uint32_t runtime_last_push_x_handle(struct Runtime *rt);

uint32_t runtime_last_push_y_handle(struct Runtime *rt);

uint64_t runtime_now_ticks(struct Runtime *rt);

int32_t runtime_phase_align_to(struct Runtime *rt, uint8_t stepper_oid, uint16_t target_phase);

int32_t runtime_phase_jog_to(struct Runtime *rt,
                             uint8_t stepper_oid,
                             uint16_t target_phase,
                             uint16_t max_microsteps_per_sample);

uint32_t runtime_push_seg_all_unused_lo(struct Runtime *rt);

int32_t runtime_query_motor_state(struct Runtime *rt,
                                  uint8_t *out_slots,
                                  int32_t *out_pos_q16,
                                  int32_t *out_vel_q16,
                                  uintptr_t max);

int32_t runtime_reset(struct Runtime *rt);

int32_t runtime_resonance_buzz(struct Runtime *rt,
                               uint8_t axis_mask,
                               uint8_t sign_mask,
                               uint32_t freq_millihz,
                               uint32_t amplitude_nm,
                               uint32_t duration_ms,
                               uint32_t ramp_ms);

int32_t runtime_seed_position(struct Runtime *rt, int32_t x_q16, int32_t y_q16, int32_t z_q16);

int32_t runtime_set_axis_mode(struct Runtime *rt, uint8_t axis_idx, uint8_t new_mode);

int32_t runtime_set_step_mode(struct Runtime *rt,
                              uint8_t stepper_idx,
                              uint8_t mode,
                              uint8_t mcu_supports_phase);

int32_t runtime_set_stepper_offset(struct Runtime *rt,
                                   uint8_t stepper_idx,
                                   int32_t delta_microsteps,
                                   uint16_t max_microsteps_per_sample);

int32_t runtime_stream_flush(struct Runtime *rt, uint32_t *out_credit_epoch);

void runtime_tick_sample(struct Runtime *rt);

int32_t runtime_ungate_pieces(struct Runtime *rt);

int32_t runtime_write_piece(struct Runtime *rt,
                            uint8_t axis_idx,
                            uint16_t start_slot,
                            uint8_t index,
                            const uint8_t *piece_ptr);

#endif  /* RUNTIME_H */
