/*
* runtime.h — generated by cbindgen.
* DO NOT EDIT. Regenerate via `cargo run -p c-api --bin gen-headers`.
*/


#ifndef RUNTIME_H
#define RUNTIME_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct Runtime {
  uint8_t _private[0];
} Runtime;

/**
 * Sentinel: `tmc_cs_oid == 0xFF` means "no TMC driver" (Pulse-only stepper).
 */
typedef struct StepperBindingRust {
  uint8_t stepper_oid;
  uint8_t tmc_cs_oid;
  uint8_t _pad[2];
} StepperBindingRust;

/**
 * Foreground-only, call under `irq_save` — the ISR mutates the front sample
 * run and a torn u64 read would fabricate a bogus stall window.
 * Returns 1 with the front sample-run window, 0 when the lane is empty,
 * negative on error. `out_occupancy` is the axis's queued sample-run count.
 */
int32_t runtime_axis_head_window(struct Runtime *rt,
                                 uint32_t axis_idx,
                                 uint64_t *out_start,
                                 uint64_t *out_end,
                                 uint32_t *out_occupancy);

int32_t runtime_bind_phase_motor(struct Runtime *rt, uint8_t motor_idx, uint8_t slot_idx);

int32_t runtime_clock_sync_request(struct Runtime *rt,
                                   uint32_t request_id,
                                   uint32_t host_send_time_lo,
                                   uint32_t host_send_time_hi,
                                   uint64_t *out_mcu_clock);

int32_t runtime_configure_axis(struct Runtime *rt,
                               uint8_t axis_idx,
                               uint8_t mode,
                               uint32_t microstep_distance_f32_bits,
                               const struct StepperBindingRust *bindings_ptr,
                               uint8_t stepper_count);

extern uint32_t runtime_cyccnt_read(void);

int32_t runtime_get_heartbeat(struct Runtime *rt,
                              uint8_t *out_engine_state,
                              uint16_t *out_fault_code,
                              uint32_t *out_retired,
                              uint64_t *out_playback_clock,
                              uintptr_t max_axes);

int32_t runtime_get_phase_state(struct Runtime *rt,
                                uint8_t stepper_oid,
                                uint8_t *out_axis_idx,
                                uint8_t *out_mode,
                                uint16_t *out_phase,
                                uint8_t *out_settled);

int32_t runtime_get_stepper_count(struct Runtime *rt, uint8_t oid);

uint32_t runtime_get_xdirect_write_count(void);

struct Runtime *runtime_handle_create(void);

uint32_t runtime_handle_fault_detail(struct Runtime *rt);

int32_t runtime_handle_last_error(struct Runtime *rt);

void runtime_handle_seed_widen(struct Runtime *rt, uint64_t baseline_widened_clock);

uint8_t runtime_handle_status(struct Runtime *rt);

uint32_t runtime_handle_tick_blocker_pc(struct Runtime *rt);

uint32_t runtime_handle_tick_counter(struct Runtime *rt);

uint64_t runtime_now_ticks(struct Runtime *rt);

int32_t runtime_phase_align_to(struct Runtime *rt, uint8_t stepper_oid, uint16_t target_phase);

int32_t runtime_phase_jog_to(struct Runtime *rt,
                             uint8_t stepper_oid,
                             uint16_t target_phase,
                             uint16_t max_microsteps_per_sample);

int32_t runtime_query_motor_state(struct Runtime *rt,
                                  uint8_t *out_slots,
                                  int32_t *out_pos_q16,
                                  int32_t *out_vel_q16,
                                  uintptr_t max);

int32_t runtime_reset(struct Runtime *rt);

int32_t runtime_sample_anchor(struct Runtime *rt, uint8_t oid, uint32_t clock, int32_t position);

int32_t runtime_sample_barrier(struct Runtime *rt, uint8_t oid, uint32_t seq);

/**
 * trsync trip: publish a halt at `halt_clock`. Safe from the trip's IRQ
 * context — the next tick applies it, so `IsrState` is never touched here.
 */
int32_t runtime_sample_halt(struct Runtime *rt, uint64_t halt_clock);

int32_t runtime_sample_overlay(struct Runtime *rt,
                               uint8_t oid,
                               uint32_t clock,
                               uint32_t interval_ticks,
                               uint8_t count,
                               const uint8_t *data,
                               uint16_t data_len);

/**
 * Executed position for `sample_get_position`. Mirrors `stepper_get_position`:
 * what actually reached the coils, not what is queued.
 */
int32_t runtime_sample_query(struct Runtime *rt,
                             uint8_t oid,
                             uint64_t *out_clock,
                             int32_t *out_position);

int32_t runtime_sample_run(struct Runtime *rt,
                           uint8_t oid,
                           uint32_t interval_ticks,
                           uint8_t count,
                           const uint8_t *data,
                           uint16_t data_len);

/**
 * Pop one fence playback has passed. Returns 1 when one was written to the
 * out params, 0 when none is ready. The caller loops until 0.
 */
int32_t runtime_sample_take_barrier_ack(struct Runtime *rt, uint8_t *out_oid, uint32_t *out_seq);

int32_t runtime_seed_axis_count(struct Runtime *rt, uint8_t axis_idx, int32_t count);

int32_t runtime_seed_position(struct Runtime *rt, int32_t x_q16, int32_t y_q16, int32_t z_q16);

int32_t runtime_set_axis_mode(struct Runtime *rt, uint8_t axis_idx, uint8_t new_mode);

int32_t runtime_set_stepper_offset(struct Runtime *rt,
                                   uint8_t stepper_idx,
                                   int32_t delta_microsteps,
                                   uint16_t max_microsteps_per_sample);

void runtime_tick_sample(struct Runtime *rt);

#endif  /* RUNTIME_H */
