[package]
name = "snapshot-viewer"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
libm = { version = "0.2", default-features = false }
wasm-bindgen = "0.2"
js-sys = "0.3"
pipeline-snapshot = { path = "../pipeline-snapshot" }
serde_json = { version = "1", features = ["float_roundtrip"] }

[profile.release]
opt-level = "s"
lto = true
