//! Build script for the runtime crate.
//!
//! Three responsibilities:
//!
//! 1. Register `cfg(loom)` so the `unexpected_cfgs` lint doesn't fire on
//!    `#![cfg(loom)]` markers in loom-only test files. Step-6 plan Phase 1
//!    Task 1.4 runs `RUSTFLAGS="--cfg loom"` against `tests/loom_*.rs`; the
//!    regular host clippy/check build doesn't set the cfg, so without this
//!    hint rustc warns on the attribute. Workspace `[lints]` inheritance
//!    prevents per-crate `[lints.rust]` overrides, so the registration goes
//!    here.
//!
//! 2. Emit sizing constants that vary per target MCU build. Reads two env
//!    vars exported by Klipper's Makefile (which sources them from the
//!    matching `CONFIG_RUNTIME_*` Kconfig values). Defaults match the H7
//!    `large` profile so host-only / sim builds (which don't go through the
//!    Klipper Makefile) still compile.
//!
//!    Spec: docs/superpowers/specs/2026-05-06-runtime-sizing-per-mcu-design.md §4.3.
//!    `RT_STORAGE_SIZE` is the byte ceiling for the C-declared `rt_storage`
//!    buffer (replaces the prior Rust-side `RT_CELL` with `#[link_section]`).
//!    See `docs/superpowers/specs/2026-05-19-mcu-c-rust-boundary-refactor-design.md`.
//!
//!    NURBS sizing constants (`MAX_CONTROL_POINTS`, `MAX_KNOT_VECTOR_LEN`,
//!    `MAX_DEGREE`) were removed in the 2026-05-20 stepping-redesign refactor;
//!    the runtime now uses uniform cubic Bézier pieces exclusively.
//!
//! 3. Pre-compute an identity-sinusoid LUT for phase stepping (Step 10).
//!    Writes `phase_lut_table.rs` into `OUT_DIR` with a `pub const LUT_ENTRIES`
//!    array of (i16, i16). Included by `rust/runtime/src/phase_lut.rs`.
//!    `f32::sin`/`cos` are not `const`, so table generation must happen here.

use std::env;
use std::fs;
use std::io::Write;
use std::path::PathBuf;

fn lookup(name: &str, default: &str) -> String {
    println!("cargo:rerun-if-env-changed={name}");
    match env::var(name) {
        Ok(s) if !s.is_empty() => s,
        _ => default.to_string(),
    }
}

fn main() {
    println!("cargo::rustc-check-cfg=cfg(loom)");
    println!("cargo:rerun-if-changed=build.rs");

    let cpn = lookup("KALICO_RUNTIME_CURVE_POOL_N", "16");
    let mpc = lookup("KALICO_RUNTIME_MAX_PIECES_PER_CURVE", "64");
    let rss = lookup("KALICO_RUNTIME_STORAGE_SIZE", "90112");

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR is set by cargo"));

    let sizing_body = format!(
        "// Auto-generated by runtime/build.rs — do not edit.\n\
         pub const CURVE_POOL_N: usize = {cpn};\n\
         pub const RT_STORAGE_SIZE: usize = {rss};\n\
         pub const MAX_PIECES_PER_CURVE: usize = {mpc};\n"
    );
    fs::write(out_dir.join("sizing.rs"), sizing_body).expect("write sizing.rs");

    gen_phase_lut(&out_dir);
}

fn gen_phase_lut(out_dir: &std::path::Path) {
    const MOTOR_PERIOD: usize = 1024;
    const CURRENT_AMPLITUDE: i16 = 248;

    let dest = out_dir.join("phase_lut_table.rs");
    let mut f = fs::File::create(&dest).expect("create phase_lut_table.rs");

    writeln!(f, "// Auto-generated by build.rs — do not edit.").unwrap();

    // Legacy `(i_a = sin, i_b = cos)` table consumed by `modulator.rs`.
    writeln!(f, "pub const LUT_ENTRIES: [(i16, i16); {MOTOR_PERIOD}] = [").unwrap();
    for i in 0..MOTOR_PERIOD {
        let angle = 2.0 * std::f64::consts::PI * (i as f64) / (MOTOR_PERIOD as f64);
        let i_a = (f64::from(CURRENT_AMPLITUDE) * angle.sin()).round() as i16;
        let i_b = (f64::from(CURRENT_AMPLITUDE) * angle.cos()).round() as i16;
        // Clamp to the i16 representable range (the multiply can produce 248.0
        // exactly at the anchors; rounding cannot escape the bound, but be
        // explicit so future amplitude changes don't silently overflow).
        let i_a = i_a.clamp(-CURRENT_AMPLITUDE, CURRENT_AMPLITUDE);
        let i_b = i_b.clamp(-CURRENT_AMPLITUDE, CURRENT_AMPLITUDE);
        writeln!(f, "    ({i_a}, {i_b}),").unwrap();
    }
    writeln!(f, "];").unwrap();

    // Plan-canonical `(coil_A = cos, coil_B = sin)` table consumed by
    // `crate::tick::dispatch_axis`. Identical amplitude and period as
    // `LUT_ENTRIES`; the pair order is swapped so the anchors match the
    // spec convention `PHASE_LUT[0] == (248, 0)` and
    // `PHASE_LUT[256] == (0, 248)`.
    writeln!(f, "pub const PHASE_LUT: [(i16, i16); PHASE_LUT_SIZE] = [").unwrap();
    for i in 0..MOTOR_PERIOD {
        let angle = 2.0 * std::f64::consts::PI * (i as f64) / (MOTOR_PERIOD as f64);
        let cos = (f64::from(CURRENT_AMPLITUDE) * angle.cos()).round() as i16;
        let sin = (f64::from(CURRENT_AMPLITUDE) * angle.sin()).round() as i16;
        let cos = cos.clamp(-CURRENT_AMPLITUDE, CURRENT_AMPLITUDE);
        let sin = sin.clamp(-CURRENT_AMPLITUDE, CURRENT_AMPLITUDE);
        writeln!(f, "    ({cos}, {sin}),").unwrap();
    }
    writeln!(f, "];").unwrap();
}
