use std::env;
use std::fs;
use std::io::Write;
use std::path::PathBuf;

fn lookup(name: &str, default: &str, is_mcu: bool) -> String {
    println!("cargo:rerun-if-env-changed={name}");
    match env::var(name) {
        Ok(s) if !s.is_empty() => s,
        _ => {
            if is_mcu {
                panic!(
                    "\n\
                     build.rs: `{name}` is missing or empty for a bare-metal MCU build.\n\
                     This variable must be exported by Klipper's Makefile from the\n\
                     `CONFIG_RUNTIME_*` Kconfig value matching the active `.config`.\n\
                     A missing value silently desyncs Rust's compile-time constant from\n\
                     the C-declared `rt_storage[]` buffer size, causing\n\
                     memory corruption at runtime (observed on F4 with a stale\n\
                     `.config`: C buffer 20480 bytes, Rust fallback 32768 bytes).\n\
                     Fix: ensure `make` is run from the Klipper tree with a current\n\
                     `.config` so the RUNTIME_* vars are in the environment\n\
                     when Cargo is invoked.\n"
                );
            }
            default.to_string()
        }
    }
}

fn parse_sizing(name: &str, default: &str, is_mcu: bool) -> usize {
    let raw = lookup(name, default, is_mcu);
    raw.parse()
        .unwrap_or_else(|_| panic!("{name} is not a valid usize: {raw}"))
}

fn main() {
    println!("cargo::rustc-check-cfg=cfg(loom)");
    println!("cargo:rerun-if-changed=build.rs");

    let is_mcu = env::var("CARGO_CFG_TARGET_OS")
        .map(|v| v == "none")
        .unwrap_or(false);

    let rss = lookup("RUNTIME_STORAGE_SIZE", "32768", is_mcu);

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR is set by cargo"));

    let sample_runs_per_lane: usize = if env::var_os("CARGO_FEATURE_SAMPLE_STEPPING").is_some() {
        parse_sizing("RUNTIME_SAMPLE_RUNS_PER_LANE", "12", is_mcu)
    } else {
        0
    };
    let sample_overlay_runs_per_lane: usize =
        if env::var_os("CARGO_FEATURE_SAMPLE_STEPPING").is_some() {
            parse_sizing("RUNTIME_SAMPLE_OVERLAY_RUNS_PER_LANE", "3", is_mcu)
        } else {
            0
        };

    let sizing_body = format!(
        "// Auto-generated by runtime/build.rs — do not edit.\n\
         #[allow(clippy::unreadable_literal)]\n\
         pub const RT_STORAGE_SIZE: usize = {rss};\n\
         pub const SAMPLE_RUNS_PER_LANE: usize = {sample_runs_per_lane};\n\
         pub const SAMPLE_OVERLAY_RUNS_PER_LANE: usize = {sample_overlay_runs_per_lane};\n"
    );
    fs::write(out_dir.join("sizing.rs"), sizing_body).expect("write sizing.rs");

    gen_phase_lut(&out_dir);
}

fn gen_phase_lut(out_dir: &std::path::Path) {
    const MOTOR_PERIOD: usize = 1024;
    const CURRENT_AMPLITUDE: i16 = 248;

    let dest = out_dir.join("phase_lut_table.rs");
    let mut f = fs::File::create(&dest).expect("create phase_lut_table.rs");

    writeln!(f, "// Auto-generated by build.rs — do not edit.").unwrap();

    // Plan-canonical `(coil_A = cos, coil_B = sin)`: the anchors match the
    // spec convention `PHASE_LUT[0] == (248, 0)` and `PHASE_LUT[256] == (0, 248)`.
    writeln!(f, "pub const PHASE_LUT: [(i16, i16); PHASE_LUT_SIZE] = [").unwrap();
    for i in 0..MOTOR_PERIOD {
        let angle = 2.0 * std::f64::consts::PI * (i as f64) / (MOTOR_PERIOD as f64);
        let cos = (f64::from(CURRENT_AMPLITUDE) * libm::cos(angle)).round() as i16;
        let sin = (f64::from(CURRENT_AMPLITUDE) * libm::sin(angle)).round() as i16;
        let cos = cos.clamp(-CURRENT_AMPLITUDE, CURRENT_AMPLITUDE);
        let sin = sin.clamp(-CURRENT_AMPLITUDE, CURRENT_AMPLITUDE);
        writeln!(f, "    ({cos}, {sin}),").unwrap();
    }
    writeln!(f, "];").unwrap();
}
