use std::env;
use std::fs;
use std::io::Write;
use std::path::PathBuf;

fn lookup(name: &str, default: &str, is_mcu: bool) -> String {
    println!("cargo:rerun-if-env-changed={name}");
    match env::var(name) {
        Ok(s) if !s.is_empty() => s,
        _ => {
            if is_mcu {
                panic!(
                    "\n\
                     build.rs: `{name}` is missing or empty for a bare-metal MCU build.\n\
                     This variable must be exported by Klipper's Makefile from the\n\
                     `CONFIG_RUNTIME_*` Kconfig value matching the active `.config`.\n\
                     A missing value silently desyncs Rust's compile-time constant from\n\
                     the C-declared `rt_storage[]` / piece-ring buffer size, causing\n\
                     memory corruption at runtime (observed on F4 with stale `.config`:\n\
                     C buffer = 73728 bytes, Rust constant fell back to 122880 bytes).\n\
                     Fix: ensure `make` is run from the Klipper tree with a current\n\
                     `.config` so the RUNTIME_* vars are in the environment\n\
                     when Cargo is invoked.\n"
                );
            }
            default.to_string()
        }
    }
}

fn parse_sizing(name: &str, default: &str, is_mcu: bool) -> usize {
    let raw = lookup(name, default, is_mcu);
    raw.parse()
        .unwrap_or_else(|_| panic!("{name} is not a valid usize: {raw}"))
}

fn main() {
    println!("cargo::rustc-check-cfg=cfg(loom)");
    println!("cargo:rerun-if-changed=build.rs");

    let is_mcu = env::var("CARGO_CFG_TARGET_OS")
        .map(|v| v == "none")
        .unwrap_or(false);

    let rss = lookup("RUNTIME_STORAGE_SIZE", "122880", is_mcu);
    let prs = lookup("RUNTIME_PIECE_RING_SIZE", "63488", is_mcu);
    let rate_str = lookup("RUNTIME_SAMPLE_RATE_HZ", "10000", is_mcu);
    let sample_rate_hz: usize = rate_str
        .parse()
        .unwrap_or_else(|_| panic!("RUNTIME_SAMPLE_RATE_HZ is not a valid usize: {rate_str}"));
    assert!(sample_rate_hz > 0, "RUNTIME_SAMPLE_RATE_HZ must be > 0");

    // Per-axis step throughput target: the 500 kHz single-edge ceiling set by
    // STEP_MIN_EDGE_DWT's 1 us edge spacing in src/stepper.c. Both constants
    // mirror the C preprocessor derivation in src/step_queue.h — keep in sync.
    const TARGET_STEP_RATE_HZ: usize = 500_000;
    let max_steps_per_sample = TARGET_STEP_RATE_HZ.div_ceil(sample_rate_hz).clamp(16, 256);
    let step_queue_depth = (2 * max_steps_per_sample).next_power_of_two();

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR is set by cargo"));

    let prs_bytes: usize = prs
        .parse()
        .unwrap_or_else(|_| panic!("RUNTIME_PIECE_RING_SIZE is not a valid usize: {prs}"));
    let total_ring_pieces = prs_bytes / 48; // each PieceEntry is 48 bytes

    let sample_runs_per_lane: usize = if env::var_os("CARGO_FEATURE_SAMPLE_STEPPING").is_some() {
        parse_sizing("RUNTIME_SAMPLE_RUNS_PER_LANE", "12", is_mcu)
    } else {
        0
    };
    let sample_overlay_runs_per_lane: usize =
        if env::var_os("CARGO_FEATURE_SAMPLE_STEPPING").is_some() {
            parse_sizing("RUNTIME_SAMPLE_OVERLAY_RUNS_PER_LANE", "3", is_mcu)
        } else {
            0
        };

    let sizing_body = format!(
        "// Auto-generated by runtime/build.rs — do not edit.\n\
         #[allow(clippy::unreadable_literal)]\n\
         pub const RT_STORAGE_SIZE: usize = {rss};\n\
         #[allow(clippy::unreadable_literal)]\n\
         pub const PIECE_RING_SIZE: usize = {prs};\n\
         #[allow(clippy::unreadable_literal)]\n\
         pub const TOTAL_RING_PIECES: usize = {total_ring_pieces};\n\
         pub const MAX_STEPS_PER_SAMPLE: usize = {max_steps_per_sample};\n\
         pub const STEP_QUEUE_DEPTH: usize = {step_queue_depth};\n\
         pub const SAMPLE_RUNS_PER_LANE: usize = {sample_runs_per_lane};\n\
         pub const SAMPLE_OVERLAY_RUNS_PER_LANE: usize = {sample_overlay_runs_per_lane};\n"
    );
    fs::write(out_dir.join("sizing.rs"), sizing_body).expect("write sizing.rs");

    gen_phase_lut(&out_dir);
}

fn gen_phase_lut(out_dir: &std::path::Path) {
    const MOTOR_PERIOD: usize = 1024;
    const CURRENT_AMPLITUDE: i16 = 248;

    let dest = out_dir.join("phase_lut_table.rs");
    let mut f = fs::File::create(&dest).expect("create phase_lut_table.rs");

    writeln!(f, "// Auto-generated by build.rs — do not edit.").unwrap();

    // Plan-canonical `(coil_A = cos, coil_B = sin)` table consumed by
    // `crate::tick::dispatch_axis`; the anchors match the spec convention
    // `PHASE_LUT[0] == (248, 0)` and `PHASE_LUT[256] == (0, 248)`.
    writeln!(f, "pub const PHASE_LUT: [(i16, i16); PHASE_LUT_SIZE] = [").unwrap();
    for i in 0..MOTOR_PERIOD {
        let angle = 2.0 * std::f64::consts::PI * (i as f64) / (MOTOR_PERIOD as f64);
        let cos = (f64::from(CURRENT_AMPLITUDE) * libm::cos(angle)).round() as i16;
        let sin = (f64::from(CURRENT_AMPLITUDE) * libm::sin(angle)).round() as i16;
        let cos = cos.clamp(-CURRENT_AMPLITUDE, CURRENT_AMPLITUDE);
        let sin = sin.clamp(-CURRENT_AMPLITUDE, CURRENT_AMPLITUDE);
        writeln!(f, "    ({cos}, {sin}),").unwrap();
    }
    writeln!(f, "];").unwrap();
}
