use crate::model::PhysicalParams;

/// Belt load-share split for one motor pair. `w` holds the constant and
/// position-linear share `w0 + w1·p` of the TOTAL belt force (inertial +
/// viscous + coulomb alike — elastic span sharing is force-agnostic) that the
/// endpoint applies antisymmetrically across `first`/`second`.
#[derive(Debug, Clone, PartialEq)]
pub struct PairSplit {
    pub first: usize,
    pub second: usize,
    pub w: [f64; 2],
}

fn fmt_float(x: f64) -> String {
    assert!(x.is_finite(), "profile value must be finite, got {x}");
    let s = format!("{x}");
    if s.contains(['.', 'e', 'E']) {
        s
    } else {
        format!("{s}.0")
    }
}

pub fn render_profile(
    p: &PhysicalParams,
    axes: &[&str],
    modes: &[&str],
    frame: &[Vec<f64>],
    rms_residual: &[f64],
    pairs: &[PairSplit],
) -> String {
    let fmt_vec = |v: &[f64]| {
        let inner: Vec<String> = v.iter().map(|&x| fmt_float(x)).collect();
        format!("[{}]", inner.join(", "))
    };
    let fmt_names = |v: &[&str]| {
        let inner: Vec<String> = v.iter().map(|a| format!("\"{a}\"")).collect();
        format!("[{}]", inner.join(", "))
    };
    let frame_rows: Vec<String> = frame.iter().map(|row| fmt_vec(row)).collect();
    let mut out = format!(
        "# generated by servo-ident; units: torque in 0.1% rated, motion in mm\n\
         version = 4\n\
         axes = {}\n\
         modes = {}\n\
         frame = [{}]\n\
         mass = {}\n\
         viscous = {}\n\
         coulomb = {}\n\
         fit_rms_residual = {}\n",
        fmt_names(axes),
        fmt_names(modes),
        frame_rows.join(", "),
        fmt_vec(&p.mass),
        fmt_vec(&p.viscous),
        fmt_vec(&p.coulomb),
        fmt_vec(rms_residual),
    );
    for ps in pairs {
        let first = axes
            .get(ps.first)
            .unwrap_or_else(|| panic!("pair first slot {} out of range", ps.first));
        let second = axes
            .get(ps.second)
            .unwrap_or_else(|| panic!("pair second slot {} out of range", ps.second));
        out.push_str(&format!(
            "\n[[pair]]\n\
             slots = [\"{first}\", \"{second}\"]\n\
             belt_position_split = {}\n",
            fmt_vec(&[ps.w[0], ps.w[1]]),
        ));
    }
    out
}

/// `per_drive_mass`: the mass ONE DRIVE perceives, units (0.1% rated) /
/// (mm/s²) — for a mode-space profile this is `m_mode · max_i |F[mode][i]|`
/// (the frame column scales the mode mass down to a single drive's torque
/// share), NOT the raw mode mass.
/// `rated_torque_nm`: motor rated torque in N·m.
/// `rot_dist_mm`: linear distance per revolution in mm/rev.
/// `rotor_inertia_kgm2`: rotor moment of inertia in kg·m².
///
/// Returns the drive load-inertia-ratio C00.06 in percent:
/// `(J_total - J_rotor) / J_rotor * 100`.
pub fn c0006_recommendation(
    per_drive_mass: f64,
    rated_torque_nm: f64,
    rot_dist_mm: f64,
    rotor_inertia_kgm2: f64,
) -> f64 {
    let j_total =
        per_drive_mass * (rated_torque_nm / 1000.0) * rot_dist_mm / (2.0 * std::f64::consts::PI);
    (j_total - rotor_inertia_kgm2) / rotor_inertia_kgm2 * 100.0
}
