/* Generated by rust/kalico-protocol/build.rs. Do not edit. */
/* Source spec: docs/superpowers/specs/2026-05-04-kalico-native-transport-design.md */
#ifndef KALICO_PROTOCOL_SCHEMA_H
#define KALICO_PROTOCOL_SCHEMA_H

#include <stdint.h>

#define KALICO_PROTO_VERSION 0x01

/* Bootstrap message type tags (fixed-layout per spec §5). */
#define KALICO_MSG_IDENTIFY 0x0001
#define KALICO_MSG_IDENTIFY_RESPONSE 0x0002

/* Schema-validated message type tags. */
#define KALICO_MSG_CONFIGURE_AXES 0x0030
#define KALICO_MSG_CONFIGURE_AXES_RESPONSE 0x0031
#define KALICO_MSG_QUERY_RUNTIME_CAPS 0x0040
#define KALICO_MSG_RUNTIME_CAPS_RESPONSE 0x0041
#define KALICO_MSG_PUSH_PIECES 0x0060
#define KALICO_MSG_PUSH_PIECES_RESPONSE 0x0061
#define KALICO_MSG_SET_TORQUE 0x0070
#define KALICO_MSG_SET_TORQUE_RESPONSE 0x0071
#define KALICO_MSG_STOP 0x0072
#define KALICO_MSG_STOP_RESPONSE 0x0073
#define KALICO_MSG_SET_DRIVE_LIMITS 0x0074
#define KALICO_MSG_SET_DRIVE_LIMITS_RESPONSE 0x0075
#define KALICO_MSG_RESTORE_DRIVE_LIMITS 0x0076
#define KALICO_MSG_RESTORE_DRIVE_LIMITS_RESPONSE 0x0077
#define KALICO_MSG_FAULT_EVENT 0x0082
#define KALICO_MSG_STATUS_HEARTBEAT 0x0083
#define KALICO_MSG_MCU_LOG 0x0084
#define KALICO_MSG_ENDSTOP_TRIP 0x0085

/* SHA-256 over canonicalized schema (excludes bootstrap). */
static const uint8_t KALICO_SCHEMA_HASH[32] = {
    0x09, 0x50, 0x89, 0x6a, 0x21, 0x56, 0xfb, 0x3d, 
    0xef, 0x93, 0xb9, 0xa7, 0x07, 0x05, 0x66, 0x95, 
    0x24, 0x6f, 0x3a, 0xe2, 0x20, 0x18, 0xd6, 0x81, 
    0x57, 0xf7, 0x7c, 0x80, 0x11, 0x93, 0x54, 0xcb
};

#endif /* KALICO_PROTOCOL_SCHEMA_H */
