/* Generated by rust/kalico-protocol/build.rs. Do not edit. */
/* Source spec: docs/superpowers/specs/2026-05-04-kalico-native-transport-design.md */
#ifndef KALICO_PROTOCOL_SCHEMA_H
#define KALICO_PROTOCOL_SCHEMA_H

#include <stdint.h>

#define KALICO_PROTO_VERSION 0x01

/* Bootstrap message type tags (fixed-layout per spec §5). */
#define KALICO_MSG_IDENTIFY 0x0001
#define KALICO_MSG_IDENTIFY_RESPONSE 0x0002

/* Schema-validated message type tags. */
#define KALICO_MSG_CONFIGURE_AXES 0x0030
#define KALICO_MSG_CONFIGURE_AXES_RESPONSE 0x0031
#define KALICO_MSG_QUERY_RUNTIME_CAPS 0x0040
#define KALICO_MSG_RUNTIME_CAPS_RESPONSE 0x0041
#define KALICO_MSG_PUSH_PIECES 0x0060
#define KALICO_MSG_PUSH_PIECES_RESPONSE 0x0061
#define KALICO_MSG_SET_TORQUE 0x0070
#define KALICO_MSG_SET_TORQUE_RESPONSE 0x0071
#define KALICO_MSG_FAULT_EVENT 0x0082
#define KALICO_MSG_STATUS_HEARTBEAT 0x0083
#define KALICO_MSG_MCU_LOG 0x0084

/* SHA-256 over canonicalized schema (excludes bootstrap). */
static const uint8_t KALICO_SCHEMA_HASH[32] = {
    0xef, 0x55, 0x7f, 0xeb, 0xcb, 0x70, 0x22, 0xcb, 
    0x5a, 0xc4, 0x41, 0x4c, 0xc5, 0x8b, 0xd4, 0xc4, 
    0xf4, 0x3c, 0x83, 0x99, 0x62, 0xf3, 0xc6, 0x18, 
    0x5c, 0x13, 0x02, 0x09, 0xa8, 0x1b, 0x0e, 0xfd
};

#endif /* KALICO_PROTOCOL_SCHEMA_H */
