/* Generated by rust/kalico-protocol/build.rs. Do not edit. */
/* Source spec: docs/superpowers/specs/2026-05-04-kalico-native-transport-design.md */
#ifndef KALICO_PROTOCOL_SCHEMA_H
#define KALICO_PROTOCOL_SCHEMA_H

#include <stdint.h>

#define KALICO_PROTO_VERSION 0x01

/* Bootstrap message type tags (fixed-layout per spec §5). */
#define KALICO_MSG_IDENTIFY 0x0001
#define KALICO_MSG_IDENTIFY_RESPONSE 0x0002

/* Schema-validated message type tags. */
#define KALICO_MSG_LOAD_CURVE_CUBIC 0x0010
#define KALICO_MSG_LOAD_CURVE_RESPONSE 0x0011
#define KALICO_MSG_PUSH_SEGMENT 0x0020
#define KALICO_MSG_PUSH_SEGMENT_RESPONSE 0x0021
#define KALICO_MSG_CONFIGURE_AXES 0x0030
#define KALICO_MSG_CONFIGURE_AXES_RESPONSE 0x0031
#define KALICO_MSG_QUERY_RUNTIME_CAPS 0x0040
#define KALICO_MSG_RUNTIME_CAPS_RESPONSE 0x0041
#define KALICO_MSG_RESET_CURVE_POOL 0x0050
#define KALICO_MSG_RESET_CURVE_POOL_RESPONSE 0x0051
#define KALICO_MSG_STATUS_EVENT 0x0080
#define KALICO_MSG_CREDIT_FREED 0x0081
#define KALICO_MSG_FAULT_EVENT 0x0082

/* SHA-256 over canonicalized schema (excludes bootstrap). */
static const uint8_t KALICO_SCHEMA_HASH[32] = {
    0x7e, 0xed, 0xa5, 0x4b, 0x84, 0x89, 0x4f, 0x5e, 
    0xff, 0x23, 0xf4, 0x18, 0xb5, 0x36, 0xcb, 0x33, 
    0x86, 0x4a, 0xd0, 0x29, 0xcd, 0xf6, 0x2d, 0x41, 
    0x3c, 0x43, 0x58, 0xfe, 0x79, 0x5a, 0x10, 0x1c
};

#endif /* KALICO_PROTOCOL_SCHEMA_H */
