/* Generated by rust/mcu-protocol/build.rs. Do not edit. */
/* Source spec: docs/superpowers/specs/2026-05-04-mcu-transport-design.md */
#ifndef MCU_PROTOCOL_SCHEMA_H
#define MCU_PROTOCOL_SCHEMA_H

#include <stdint.h>

#define MCU_PROTO_VERSION 0x01

/* Bootstrap message type tags (fixed-layout per spec §5). */
#define MCU_MSG_IDENTIFY 0x0001
#define MCU_MSG_IDENTIFY_RESPONSE 0x0002

/* Schema-validated message type tags. */
#define MCU_MSG_CONFIGURE_AXES 0x0030
#define MCU_MSG_CONFIGURE_AXES_RESPONSE 0x0031
#define MCU_MSG_QUERY_RUNTIME_CAPS 0x0040
#define MCU_MSG_RUNTIME_CAPS_RESPONSE 0x0041
#define MCU_MSG_QUERY_MOTOR_STATE 0x0044
#define MCU_MSG_MOTOR_STATE_RESPONSE 0x0045
#define MCU_MSG_PUSH_PIECES 0x0060
#define MCU_MSG_PUSH_PIECES_RESPONSE 0x0061
#define MCU_MSG_START_CAPTURE 0x0068
#define MCU_MSG_START_CAPTURE_RESPONSE 0x0069
#define MCU_MSG_STOP_CAPTURE 0x006a
#define MCU_MSG_STOP_CAPTURE_RESPONSE 0x006b
#define MCU_MSG_SET_TORQUE 0x0070
#define MCU_MSG_SET_TORQUE_RESPONSE 0x0071
#define MCU_MSG_STOP 0x0072
#define MCU_MSG_STOP_RESPONSE 0x0073
#define MCU_MSG_SET_DRIVE_LIMITS 0x0074
#define MCU_MSG_SET_DRIVE_LIMITS_RESPONSE 0x0075
#define MCU_MSG_RESTORE_DRIVE_LIMITS 0x0076
#define MCU_MSG_RESTORE_DRIVE_LIMITS_RESPONSE 0x0077
#define MCU_MSG_RESUME_STREAM 0x0078
#define MCU_MSG_RESUME_STREAM_RESPONSE 0x0079
#define MCU_MSG_SEED_SERVO_HOME 0x007a
#define MCU_MSG_SEED_SERVO_HOME_RESPONSE 0x007b
#define MCU_MSG_FAULT_EVENT 0x0082
#define MCU_MSG_STATUS_HEARTBEAT 0x0083
#define MCU_MSG_MCU_LOG 0x0084
#define MCU_MSG_ENDSTOP_TRIP 0x0085

/* SHA-256 over canonicalized schema (excludes bootstrap). */
static const uint8_t MCU_SCHEMA_HASH[32] = {
    0x79, 0xb3, 0x78, 0xfb, 0x13, 0x22, 0xf8, 0xc9, 
    0x1a, 0xd0, 0x75, 0x52, 0xc7, 0x0e, 0x19, 0x09, 
    0x11, 0xf5, 0x38, 0xb8, 0x1e, 0x38, 0x2c, 0xdf, 
    0x29, 0x35, 0x39, 0xbd, 0xf2, 0x19, 0xeb, 0x6e
};

#endif /* MCU_PROTOCOL_SCHEMA_H */
