/*
* kalico_runtime.h — generated by cbindgen.
* DO NOT EDIT. Regenerate via `cargo run -p kalico-c-api --bin gen-headers`.
* See docs/superpowers/specs/2026-04-28-layer-4-mcu-framework-stub-design.md.
*/


#ifndef KALICO_RUNTIME_H
#define KALICO_RUNTIME_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct KalicoRuntime {
  uint8_t _private[0];
} KalicoRuntime;

/**
 * Sentinel: `tmc_cs_oid == 0xFF` means "no TMC driver" (Pulse-only stepper).
 */
typedef struct StepperBindingRust {
  uint8_t stepper_oid;
  uint8_t tmc_cs_oid;
  uint8_t _pad[2];
} StepperBindingRust;

int32_t kalico_runtime_clock_sync_request(struct KalicoRuntime *rt,
                                          uint32_t request_id,
                                          uint32_t host_send_time_lo,
                                          uint32_t host_send_time_hi,
                                          uint64_t *out_mcu_clock);

int32_t kalico_runtime_commit_head(struct KalicoRuntime *rt, uint8_t axis_idx, uint32_t new_head);

int32_t kalico_runtime_configure_axis(struct KalicoRuntime *rt,
                                      uint8_t axis_idx,
                                      uint8_t mode,
                                      uint32_t microstep_distance_f32_bits,
                                      uint16_t ring_depth,
                                      const struct StepperBindingRust *bindings_ptr,
                                      uint8_t stepper_count);

int32_t kalico_runtime_discard_pending(struct KalicoRuntime *rt);

uint32_t kalico_runtime_enqueue_success_lo(struct KalicoRuntime *rt);

double kalico_runtime_get_axis_accumulator(struct KalicoRuntime *rt, uint8_t oid);

float kalico_runtime_get_axis_motor(struct KalicoRuntime *rt, uint8_t oid);

uint32_t kalico_runtime_get_dispatcher_floor_cycles(void);

int32_t kalico_runtime_get_heartbeat(struct KalicoRuntime *rt,
                                     uint8_t *out_engine_state,
                                     uint16_t *out_fault_code,
                                     uint32_t *out_retired,
                                     uintptr_t max_axes);

void kalico_runtime_get_last_timing(struct KalicoRuntime *rt,
                                    uint64_t *now_out,
                                    uint64_t *t_start_out,
                                    uint64_t *duration_out);

int32_t kalico_runtime_get_occupancy(struct KalicoRuntime *rt,
                                     uint32_t *out_occupancy,
                                     uintptr_t max_axes);

uint32_t kalico_runtime_get_sample_period_cycles(void);

uint8_t kalico_runtime_get_step_mode(struct KalicoRuntime *rt, uint8_t stepper_idx);

int32_t kalico_runtime_get_stepper_count(struct KalicoRuntime *rt, uint8_t oid);

uint32_t kalico_runtime_get_tick_counter(struct KalicoRuntime *rt);

uint32_t kalico_runtime_get_xdirect_write_count(void);

int32_t kalico_runtime_install_step_queues(struct KalicoRuntime *rt, uint8_t *queues);

uint32_t kalico_runtime_last_push_consumers_remaining(struct KalicoRuntime *rt);

uint32_t kalico_runtime_last_push_x_handle(struct KalicoRuntime *rt);

uint32_t kalico_runtime_last_push_y_handle(struct KalicoRuntime *rt);

uint64_t kalico_runtime_now_ticks(struct KalicoRuntime *rt);

uint32_t kalico_runtime_push_seg_all_unused_lo(struct KalicoRuntime *rt);

uint16_t kalico_runtime_query_phase_config(struct KalicoRuntime *rt, uint8_t motor_idx);

int32_t kalico_runtime_reset(struct KalicoRuntime *rt);

int32_t kalico_runtime_seed_position(struct KalicoRuntime *rt,
                                     int32_t x_q16,
                                     int32_t y_q16,
                                     int32_t z_q16);

int32_t kalico_runtime_set_axis_mode(struct KalicoRuntime *rt, uint8_t axis_idx, uint8_t new_mode);

int32_t kalico_runtime_set_step_mode(struct KalicoRuntime *rt,
                                     uint8_t stepper_idx,
                                     uint8_t mode,
                                     uint8_t mcu_supports_phase);

int32_t kalico_runtime_set_stepper_offset(struct KalicoRuntime *rt,
                                          uint8_t stepper_idx,
                                          int32_t delta_microsteps,
                                          uint16_t max_microsteps_per_sample);

int32_t kalico_runtime_stream_flush(struct KalicoRuntime *rt, uint32_t *out_credit_epoch);

void kalico_runtime_tick_sample(struct KalicoRuntime *rt);

int32_t kalico_runtime_write_piece(struct KalicoRuntime *rt,
                                   uint8_t axis_idx,
                                   uint16_t start_slot,
                                   uint8_t index,
                                   const uint8_t *piece_ptr);

extern uint32_t runtime_cyccnt_read(void);

int32_t runtime_handle_check_blob_version(const uint8_t *payload_ptr, uint32_t payload_len);

struct KalicoRuntime *runtime_handle_create(void);

uint32_t runtime_handle_fault_detail(struct KalicoRuntime *rt);

float runtime_handle_get_axis_steps_per_mm(struct KalicoRuntime *rt, uint8_t oid);

int32_t runtime_handle_last_error(struct KalicoRuntime *rt);

uint32_t runtime_handle_last_modulated_duration_lo(struct KalicoRuntime *rt);

uint32_t runtime_handle_last_modulated_elapsed_lo(struct KalicoRuntime *rt);

uint32_t runtime_handle_last_retire_consumers_after_clear(struct KalicoRuntime *rt);

uint32_t runtime_handle_modulated_retire_attempts(struct KalicoRuntime *rt);

uint32_t runtime_handle_modulated_retire_successes(struct KalicoRuntime *rt);

void runtime_handle_seed_widen(struct KalicoRuntime *rt, uint64_t baseline_widened_clock);

uint8_t runtime_handle_status(struct KalicoRuntime *rt);

uint32_t runtime_handle_tick_blocker(struct KalicoRuntime *rt);

uint32_t runtime_handle_tick_blocker_exc(struct KalicoRuntime *rt);

uint32_t runtime_handle_tick_blocker_pc(struct KalicoRuntime *rt);

uint32_t runtime_handle_tick_counter(struct KalicoRuntime *rt);

uint64_t runtime_handle_widened_now(struct KalicoRuntime *rt);

#endif  /* KALICO_RUNTIME_H */
