/*
* kalico_nurbs.h — generated by cbindgen.
* DO NOT EDIT. Regenerate via `cargo run -p kalico-c-api --bin gen-headers`.
* See docs/superpowers/specs/2026-04-26-nurbs-evaluation-library-design.md.
*/


#ifndef KALICO_NURBS_H
#define KALICO_NURBS_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct kalico_nurbs_ArcLengthTableRef_f32 kalico_nurbs_ArcLengthTableRef_f32;

typedef struct kalico_nurbs_ScalarNurbsRef_f32 kalico_nurbs_ScalarNurbsRef_f32;

typedef struct kalico_nurbs_VectorNurbsRef_f32__3 kalico_nurbs_VectorNurbsRef_f32__3;

float kalico_nurbs_eval_f32(const struct kalico_nurbs_ScalarNurbsRef_f32 *curve, float u);

float kalico_nurbs_param_from_arc_length_f32(const struct kalico_nurbs_ArcLengthTableRef_f32 *table,
                                             float s);

void kalico_nurbs_vector_eval_3_f32(const struct kalico_nurbs_VectorNurbsRef_f32__3 *curve,
                                    float u,
                                    float *out);

int32_t kalico_runtime_clock_sync_request(kalico_nurbs_KalicoRuntime *rt,
                                          uint32_t request_id,
                                          uint32_t host_send_time_lo,
                                          uint32_t host_send_time_hi,
                                          uint64_t *out_mcu_clock);

int32_t kalico_runtime_commit_head(kalico_nurbs_KalicoRuntime *rt,
                                   uint8_t axis_idx,
                                   uint32_t new_head);

int32_t kalico_runtime_configure_axis(kalico_nurbs_KalicoRuntime *rt,
                                      uint8_t axis_idx,
                                      uint8_t mode,
                                      uint32_t microstep_distance_f32_bits,
                                      uint16_t ring_depth,
                                      const kalico_nurbs_StepperBindingRust *bindings_ptr,
                                      uint8_t stepper_count);

int32_t kalico_runtime_discard_pending(kalico_nurbs_KalicoRuntime *rt);

uint32_t kalico_runtime_enqueue_success_lo(kalico_nurbs_KalicoRuntime *rt);

double kalico_runtime_get_axis_accumulator(kalico_nurbs_KalicoRuntime *rt, uint8_t oid);

float kalico_runtime_get_axis_motor(kalico_nurbs_KalicoRuntime *rt, uint8_t oid);

uint32_t kalico_runtime_get_dispatcher_floor_cycles(void);

int32_t kalico_runtime_get_heartbeat(kalico_nurbs_KalicoRuntime *rt,
                                     uint8_t *out_engine_state,
                                     uint16_t *out_fault_code,
                                     uint32_t *out_retired,
                                     uintptr_t max_axes);

void kalico_runtime_get_last_timing(kalico_nurbs_KalicoRuntime *rt,
                                    uint64_t *now_out,
                                    uint64_t *t_start_out,
                                    uint64_t *duration_out);

int32_t kalico_runtime_get_occupancy(kalico_nurbs_KalicoRuntime *rt,
                                     uint32_t *out_occupancy,
                                     uintptr_t max_axes);

uint32_t kalico_runtime_get_sample_period_cycles(void);

uint8_t kalico_runtime_get_step_mode(kalico_nurbs_KalicoRuntime *rt, uint8_t stepper_idx);

int32_t kalico_runtime_get_stepper_count(kalico_nurbs_KalicoRuntime *rt, uint8_t oid);

uint32_t kalico_runtime_get_tick_counter(kalico_nurbs_KalicoRuntime *rt);

uint32_t kalico_runtime_get_xdirect_write_count(void);

int32_t kalico_runtime_install_step_queues(kalico_nurbs_KalicoRuntime *rt, uint8_t *queues);

uint32_t kalico_runtime_last_push_consumers_remaining(kalico_nurbs_KalicoRuntime *rt);

uint32_t kalico_runtime_last_push_x_handle(kalico_nurbs_KalicoRuntime *rt);

uint32_t kalico_runtime_last_push_y_handle(kalico_nurbs_KalicoRuntime *rt);

uint64_t kalico_runtime_now_ticks(kalico_nurbs_KalicoRuntime *rt);

uint32_t kalico_runtime_push_seg_all_unused_lo(kalico_nurbs_KalicoRuntime *rt);

uint16_t kalico_runtime_query_phase_config(kalico_nurbs_KalicoRuntime *rt, uint8_t motor_idx);

int32_t kalico_runtime_reset(kalico_nurbs_KalicoRuntime *rt);

int32_t kalico_runtime_seed_position(kalico_nurbs_KalicoRuntime *rt,
                                     int32_t x_q16,
                                     int32_t y_q16,
                                     int32_t z_q16);

int32_t kalico_runtime_set_axis_mode(kalico_nurbs_KalicoRuntime *rt,
                                     uint8_t axis_idx,
                                     uint8_t new_mode);

int32_t kalico_runtime_set_step_mode(kalico_nurbs_KalicoRuntime *rt,
                                     uint8_t stepper_idx,
                                     uint8_t mode,
                                     uint8_t mcu_supports_phase);

int32_t kalico_runtime_set_stepper_offset(kalico_nurbs_KalicoRuntime *rt,
                                          uint8_t stepper_idx,
                                          int32_t delta_microsteps,
                                          uint16_t max_microsteps_per_sample);

int32_t kalico_runtime_stream_flush(kalico_nurbs_KalicoRuntime *rt, uint32_t *out_credit_epoch);

void kalico_runtime_tick_sample(kalico_nurbs_KalicoRuntime *rt);

int32_t kalico_runtime_write_piece(kalico_nurbs_KalicoRuntime *rt,
                                   uint8_t axis_idx,
                                   uint16_t start_slot,
                                   uint8_t index,
                                   const uint8_t *piece_ptr);

int32_t runtime_handle_check_blob_version(const uint8_t *payload_ptr, uint32_t payload_len);

uint32_t runtime_handle_fault_detail(kalico_nurbs_KalicoRuntime *rt);

float runtime_handle_get_axis_steps_per_mm(kalico_nurbs_KalicoRuntime *rt, uint8_t oid);

uint32_t runtime_handle_last_modulated_duration_lo(kalico_nurbs_KalicoRuntime *rt);

uint32_t runtime_handle_last_modulated_elapsed_lo(kalico_nurbs_KalicoRuntime *rt);

uint32_t runtime_handle_last_retire_consumers_after_clear(kalico_nurbs_KalicoRuntime *rt);

uint32_t runtime_handle_modulated_retire_attempts(kalico_nurbs_KalicoRuntime *rt);

uint32_t runtime_handle_modulated_retire_successes(kalico_nurbs_KalicoRuntime *rt);

void runtime_handle_seed_widen(kalico_nurbs_KalicoRuntime *rt, uint64_t baseline_widened_clock);

uint32_t runtime_handle_tick_blocker(kalico_nurbs_KalicoRuntime *rt);

uint32_t runtime_handle_tick_blocker_exc(kalico_nurbs_KalicoRuntime *rt);

uint32_t runtime_handle_tick_blocker_pc(kalico_nurbs_KalicoRuntime *rt);

uint64_t runtime_handle_widened_now(kalico_nurbs_KalicoRuntime *rt);

#endif  /* KALICO_NURBS_H */
